### ISSUE TITLE
UI and Layout Enhancements for Improved User Experience

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#111]
### Overview
This issue focuses on improving the visual design and  layout stability of the app to enhance the overall user experience.

### Scope of Work

1. *Fix the Favicon Display Issue*  
   Ensure the favicon displays correctly across all browsers and devices.

2. *SEO Enhancements*  
   - Add appropriate Meta tags (image and description) to improve search engine visibility.
   - Update Open Graph (OG) tags to support better sharing previews on social media.

3. *Set Fixed Width for Layout*  
   Define a consistent, fixed width to prevent overstretching on larger screens, ensuring a visually stable design.

**Comment by Joy-Adah** [comment]
Hi @princeibs can I take this up?
