### ISSUE TITLE
Dice Selection Interface

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#115]
![image](https://github.com/user-attachments/assets/42410d3a-e612-4e3e-b292-1c961b9fe357)

### Description
Create a dice selection system with three distinct dice styles.

#### Requirements
- [ ] Make sure to update the gamestate context provider of you implementation 
- [ ] Implement three dice options:
  - Golden Dice
  - Retro Dice
  - Unique Dice
- [ ] Add 3D rotation preview on hover using ThreeJS with the glTF 3D model if there no 3D model provided you can use a 3D react library component

### ETA
This issue is expected to be completed within 2 days or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

**Comment by CollinsC1O** [comment]
I’d like to work on this.

**Comment by Supa-mega** [comment]
Can I jump on this task?

**Comment by KevinLatino** [comment]
Hello My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

 I’ll implement a dice selection system with three options: Golden Dice, Retro Dice, and Unique Dice. I’ll update the game state context and integrate a 3D rotation preview using Three.js and glTF models on hover, allowing players to interact with and preview the dice styles.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

I have already been a contributor to this project on one of the previous odhacks

**Comment by martinvibes** [comment]
i'm a frontend dev and blockchain dev 
May I try my hand at this?
i would love to work on this and get it done

**Comment by MullerTheScientist** [comment]
I'd love to take care of this task

**Comment by blessingbytes** [comment]
i would love to work on this issue

**Comment by ONEONUORA** [comment]
Can I start working on this? I am a full stack and cairo developer. ETA 24 hrs

**Comment by estherbreath** [comment]
I'd like to work on this, please.

to implement the Dice Selection Interface, I will do the following:

1. Create a component for each dice style (Golden, Retro, Unique) with corresponding 3D models or SVG representations.
2. Implement a state variable to track the selected dice style and update the gamestate context provider accordingly.
3. Use ThreeJS or a 3D React library to add hover effects and 3D rotation previews for each dice option.

**Comment by Ndifreke000** [comment]
May I be assigned to this?

**Comment by abdegenius** [comment]
Can I take this from here?

**Comment by chigozzdevv** [comment]
Hello, good day :)
please can I take up this?

**Comment by Pvsaint** [comment]
I’d love to work on this task please, I'm Victor Peter, a front-end and smart contract developer. I promise to write a pixel perfect code.

**Comment by Akshola00** [comment]
I’d like to help with this.

**Comment by aniruddhaaps** [comment]
To address this issue, I would implement a dice selection system with three styles: Golden Dice, Retro Dice, and Unique Dice. Implement a 3D rotation preview on hover using ThreeJS or a React 3D library component, and allow for the use of glTF 3D models. Update the gamestate context provider to reflect the selected dice style for proper state management.

**Comment by ShantelPeters** [comment]
Can I contribute to this one?

**Comment by psychemist** [comment]
Hi. I have played your Ludo game, am fascinated by the gameplay and would love to be a contributor on this project. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have experience building a React based game with dynamic routing and full player interactivity. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects. 

I would create the dice selection system by:

- Updating the game state context provider to track the selected dice style.
- Implementing three distinct dice options: Golden Dice, Retro Dice, and Unique Dice, with corresponding visuals.
- Using Three.js or a 3D React library component to create a 3D rotation preview for each dice style, showing the dice rotating inhover state.
- Ensuring the dice rotation effect is smooth and interactive.
- Testing the dice styles across devices for performance and responsiveness to ensure a unified user experience.
- Including a short GIF in my PR submission for confirmation


I aim to complete this task within 3 days of being assigned and setting up my development environment, with a PR request in the first 24 hours.

Thank you for the opportunity and I look forward to working with you.

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll install necessary dependencies such as three, @react-three/fiber, @react-three/drei, and glTFLoader. I’ll store .glTF models for Golden Dice, Retro Dice, and Unique Dice in public/assets/dice/
2.⁠ ⁠⁠I’ll use Canvas from @react-three/fiber to render 3D models, load .glTF files with useGLTF and enable rotation preview using OrbitControls with autoRotate. I’ll map dice options into interactive UI cards, include DicePreview for each option and use onClick to update the selected dice state.
3.⁠ ⁠⁠I’ll integrate a GameStateContext provider. I’ll define selectedDice and setSelectedDice in the global context and also I’ll update state on dice selection.
4.⁠ ⁠⁠I’ll add hover effects to trigger 3D rotation using OrbitControls and implement responsive styling for hover previews.
5.⁠ ⁠⁠I’ll test to verify model rendering and interactivity, validate state updates on selection an test responsiveness and hover behaviors across devices.

Kindly assign me please, I’m ready to work.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by vestor-dev** [comment]
Ihey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

ETA: 72hrs

**Comment by 1nonlypiece** [comment]
May I handle this issue?

**Comment by TheSQLguy** [comment]
I am new to open source.
To address this issue, I would implement a dice selection system with three styles: Golden Dice, Retro Dice, and Unique Dice. Implement a 3D rotation preview on hover using ThreeJS or a React 3D library component, and allow for the use of glTF 3D models. Update the gamestate context provider to reflect the selected dice style for proper state management.

**Comment by Michaelkingsdev** [comment]
I'd love to give this a go.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by suhas-sensei** [comment]
May I be assigned to this? I'll implement a dice selection system with three unique styles using ThreeJS for 3D rotation previews, integrating with the gamestate context. Having experience with ThreeJS and React state management, I'll create smooth 3D dice previews and proper selection handling.

**Comment by DuendexCR** [comment]
Can I take this issue?

**Comment by greatest0falltime** [comment]
Is it okay if I take this?

**Comment by Nityam573** [comment]
Can I attempt this issue?

**Comment by ekumamatthew** [comment]
Can I start working on this?

**Comment by josephchimebuka** [comment]
Hello  I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute I will follow the description above to create a dice selection system with three distinct dice styles in 3 days
