### ISSUE TITLE
Color Selection System

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#116]
![image](https://github.com/user-attachments/assets/2ea9d6b4-2500-4c6b-8e0d-bb9f29dcfc29)

### Description
Create a color selection interface with gem-styled options for player colors.

#### Requirements
- [ ] Make sure to update the game state context provider of your implementation `game-hook.tsx`
- [ ] Implement four color options:
  - Blue gem
  - Green gem
  - Orange gem
  - Red gem
- [ ] Add hover effects for gems
- [ ] Show selected state
- [ ] Implement selection confirmation
- [ ] Add close button functionality

#### Technical Notes
- Use SVG for gem graphics
- Implement proper color accessibility like keyboard selection
- Add subtle animations for selection
---

### ETA
This issue is expected to be completed within 2 days or being assigned. Failure to create a pull request or draft pull request will lead to the contributor being unassigned

**Comment by CollinsC1O** [comment]
May I pick this up?

**Comment by Supa-mega** [comment]
May I try my hand at this?

**Comment by Kingsuite** [comment]
Can I contribute to this one?

**Comment by abdegenius** [comment]
I’d love to work on this task.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

I have already been a contributor to this project on one of the previous odhacks

**Comment by Luluameh** [comment]
Hi, I’m a frontend developer with experience in TypeScript, and I’m excited to work on the Color Selection System for your game. I’ve reviewed the requirements and am ready to implement this feature.

Plan to Solve the Issue:

Implement a color selection interface with gem-styled options (Blue, Green, Orange, and Red) using SVG graphics.
Add hover effects to the gems for an interactive experience.
Implement a selected state for the gem, ensuring visual feedback when a color is chosen.
Integrate the selection with the game state using game-hook.tsx, ensuring the selected color updates properly.
Add a confirmation button to finalize the selection and a close button to exit the color selection.
Ensure accessibility features are in place, including keyboard selection and focus states.
Add subtle animations to make the selection process smooth and engaging.
Estimated Completion Time: 2 days

I’m looking forward to contributing to the game’s UI and enhancing the player experience!

**Comment by No-bodyq** [comment]
Would love to tackle this!

**Comment by anonfedora** [comment]
Hi, I'm Eleazar a fullstack blockchain developer (proficient in Cairo, Rust, Reactjs, Nextjs),
ETA: 72 hours

**Comment by 7-falseparfait** [comment]
Can I try solving this issue?

I am a Front-end and Smart Contract Developer proficient in Tailwind CSS, Next.js, TypeScript, and JavaScript. I also specialize in creating clear and comprehensive documentation. I would be thrilled to contribute to this project and add value with my skills.

**Comment by blessingbytes** [comment]
May I try my hand at this?

**Comment by MullerTheScientist** [comment]
I'd be happy to address this issue

**Comment by starknetbrother** [comment]
Would love to tackle this!

**Comment by Belloabraham121** [comment]
Hey! I'm Iteooluwakisi.
Member of Web3bridge. I have contributed before to other projects like:
• CoinSafe 
• Scaffold-ETH
• BuidlGuidl
Can I work on this issue?
Plan to Solve the Issue:
Study the codebase to understand the current structure and functionality.
Understand the problem that needs to be solved by thoroughly reading the issue details.
Leverage all provided resources within the issue to get a better grasp of the task at hand.
If I encounter roadblocks, I will ask questions ASAP in the relevant group/chat to move forward effectively.
I will open a PR and wait for your feedback.

**Comment by emarc99** [comment]
I'd love to give this a go. I have built an animation-based web project, and have graphics design experince as well. coupled woth my React/next js, tailwind, animation libraries, I can get it done in 3 days.

**Comment by Ndifreke000** [comment]
I'd like to take this issue.

**Comment by chigozzdevv** [comment]
Hello, please let me tackle this fast and well. Thanks

**Comment by aniruddhaaps** [comment]
To address this issue, I would implement a settings panel with sound and music volume sliders having 10-step indications and the appropriate icons. A difficulty selection button should exist, defaulted to Beginner, also Experienced, Professional. Another option to customize the background. The gamestate context provider should be updated on game-hook.tsx for state management purposes, including a close button. It should be able to maintain smooth UI/UX for hassle-free integration.

**Comment by ShantelPeters** [comment]
Can I tackle this one?

**Comment by psychemist** [comment]
Hi. I am a fullstack web developer and a recent alumni of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have experiencebuilding a React based game withdynamic routing and full player interactivity. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects. I have played your Ludo game, am fascinated by the gameplay and would love to be a contributor on this project.

I would create the color selection interface by:

- Updating the game state context provider in game-hook.tsx to manage the selected color state.
- Implementing four color options: Blue gem, Green gem, Orange gem, and Red gem, using SVG for the gem graphics to ensure clear and scalable icons.
- Adding hover effects for each gem during interaction and a selected state to visually highlight the currently chosen gem.
- Implementing a selection confirmation, such as a button or an auto modal when a color is selected, and updating the state with the selected color.
- Including a close button to dismiss the color selection interface, ensuring state preserveation.
- Adding accessibility for keyboard users, allowing players to navigate through the options using the arrow keys.
- Implementing subtle animations (e.g. glowing effects) during gem selection to enhance the user experience.
- Testing across platforms to ensure the interface is responsive, accessible, and works on remote environments

I aim to complete this task within 36 hours of being assigned and setting up my development environment.

Thank you for the opportunity and I look forward to working with you.

**Comment by Amarjeet325** [comment]
Can I take care of this issue?

**Comment by od-hunter** [comment]
Hi, please can I be assigned this please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

To solve this issue, I'll take the following steps:
1. I'll extend game-hook.tsx to include a selectedColor state and a setSelectedColor function for managing player color selection.
2. I'll use an array of gem color options (blue, green, orange, red) to dynamically render SVG elements in the component using .map().
3. I'll attach onClick events to each gem for color selection.
Add a closePanel function to handle the close button functionality and reset state if necessary.
4. I'll apply hover effects (transform: scale(1.1)) and selection animations (e.g., pulse effect) using @keyframes or CSS transitions.
5. I'll use tabIndex for navigability and add an onKeyDown event to handle Enter key selection for gems and import optimized SVG assets for gem graphics and dynamically apply colors using CSS fill properties.
6. Lastly, I'll write unit tests for game-hook.tsx to validate setSelectedColor updates, create integration tests to simulate user interactions (mouse and keyboard) and verify state changes and also perform cross-browser testing to ensure consistent behavior and rendering.

Kindly assign me please, I'm ready to work.

**Comment by codeZe-us** [comment]
Please can I take this?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by Jagadeeshftw** [comment]
Hello, I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by vestor-dev** [comment]
Ihey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

ETA: 12hrs

**Comment by 1nonlypiece** [comment]
Can I handle this task?

**Comment by TheSQLguy** [comment]
I am new to opensource
To address this issue, I would implement a settings panel with sound and music volume sliders having 10-step indications and the appropriate icons. A difficulty selection button should exist, defaulted to Beginner, also Experienced, Professional. Another option to customize the background. The gamestate context provider should be updated on game-hook.tsx for state management purposes, including a close button. It should be able to maintain smooth UI/UX for hassle-free integration.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Michaelkingsdev** [comment]
Is it okay if I take this?

**Comment by DuendexCR** [comment]
Can I take this issue?

**Comment by greatest0falltime** [comment]
I'd love to work on this!

**Comment by ekumamatthew** [comment]
I'd love to give this a go.

**Comment by CHEF-SAVY** [comment]
Hello, I'm Isaac a frontend dev.
I'm a new contributor to this project and I'd appreciate it if i can be given the opportunity to tackle this issue.
ETA: 2days

**Comment by josephchimebuka** [comment]
Hello This is my first time to contribute to this repo ill appreciate the opportunity to contribute. I will ensure to create a color selection interface with gem-styled options for player colors in 2-3 days
