### ISSUE TITLE
Update contracts documentation

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#122]
The contracts were migrated to Dojo V1 but the corresponding documentation was not updated accordingly.

- Update the necessary documentation in the contracts that was during migration to Dojo V1

**Comment by MullerTheScientist** [comment]
I'd love to Tackle this issue

**Comment by Kingsuite** [comment]
Could I take a shot at this? I love working on documentations

**Comment by SYLVIANNORUKA** [comment]
Can I jump on this task?’ll update the codebase by creating a detailed README.md with everything new contributors need, like a project overview, setup steps, and contribution guidelines. I’ll also add comments in the code, document the APIs, and include an architecture overview with examples. Once that’s done, I’ll test the documentation by getting feedback from someone new to the project and refine it. To keep things organized, I’ll set a standard for maintaining the documentation during future updates.

**Comment by starknetbrother** [comment]
Is it okay if I take this?

**Comment by Birdmannn** [comment]
Hello dev. I'm Pascal and I am a new contributor to the project. I have experience in writing cairo smart contracts, and I sure know how to document it well. I shall read the code base and dojo's documentation thoroughly, and update the documentation of the contracts where necessary. ETA < 3 days

**Comment by Ndifreke000** [comment]
Can I take care of this issue?

**Comment by abdegenius** [comment]
Can I take this issue?

**Comment by chigozzdevv** [comment]
Hello, good day :)
Can I take this issue?
You can check my docs samples here: medium.com/@chigozzdev

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by Akshola00** [comment]
Hello, I'm Akinshola Akinniyi, a smart contract developer with experience in StarkNet and Cairo. I gained a solid foundation in decentralized applications and have contributed to multiple projects on OnlyDust, focusing on smart contract development and documentation.

I would be happy to help update the necessary documentation for the contracts that were migrated to Dojo V1. With my experience in writing and maintaining clear documentation alongside smart contract development, I’m confident I can ensure the documentation aligns with the recent migration. Please assign me this task—I look forward to contributing to the project!

**Comment by aniruddhaaps** [comment]
Identify all the code annotations, comments, and README files referring to the previous version and update these to have the correct information for Dojo V1, which reflects what's in effect regarding the updated API and architectural changes. Confirm that the documentation is consistent with the most up-to-date codebase.

**Comment by Naomi-Gift** [comment]
Could I be assigned to this?
I am a web3 developer and  a technical writer , Will do this perfectly if i an being assigned

**Comment by Kaminar-i** [comment]
Please can I take on this issue

**Comment by ShantelPeters** [comment]
Can I try solving this issue?

**Comment by vestor-dev** [comment]
hey sir i would love to work on this issue 
i'm a blockchain dev and i would love to handle this issue 
assign me and i'll get to work

**Comment by Benjtalkshow** [comment]
Could I take over this issue?

**Comment by Jagadeeshftw** [comment]
I’d love to work on this issue as I have strong experience in developing comprehensive and user-focused documentation. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by TheSQLguy** [comment]
I am new to open source.
Identify all the code annotations, comments, and README files referring to the previous version and update these to have the correct information for Dojo V1, which reflects what's in effect regarding the updated API and architectural changes. Confirm that the documentation is consistent with the most up-to-date codebase.

**Comment by jahrulezfrancis** [comment]
I would really love to work on this issue. I’ll update the necessary documentation in the contracts to reflect the migration to Dojo V1. This will ensure that the documentation aligns with the latest changes and provides accurate information for developers. I can complete this task within 24 hours.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by ikezuby2012** [comment]
Can I be assigned to this?

**Comment by DuendexCR** [comment]
I'd like to take this issue.

**Comment by blessingbytes** [comment]
I am happy to provide the necessary documentations to support the Dojo V1 migration for all the contracts. Let's do this!

**Comment by Nityam573** [comment]
I'd be happy to do this.

**Comment by vibenedict** [comment]
@ikezuby2012 what's the update on this?

**Comment by mimiprosper** [comment]
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust.
If assigned this i would complete it within 1 day.

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke
