### ISSUE TITLE
Leaderboard UI design 

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#130]
![Leaderboard](https://hackmd.io/_uploads/Byww1w_E1l.png)

### Description

Implement leaderboard UI (it should be responsive)

#### Requirements
- [ ] Implement account list with:
  - Account number
  - Account name
  - Points display
  - Rank display e.t.c
- [ ] Add close button functionality
- [ ] Implement the toggle buttons "Global Ranking" & "Friends Ranking" tabs

**Comment by Jagadeeshftw** [comment]
Is it okay if I take this?

**Comment by greatest0falltime** [comment]
Can I jump on this task?

**Comment by 1nonlypiece** [comment]
Could I grab this task?

**Comment by olisaagbafor** [comment]
Can I take this from here?

**Comment by martinvibes** [comment]
Is it okay if I take this?
Kindly assign :)

**Comment by vestor-dev** [comment]
Can I tackle this one?
Would love to do this

**Comment by emarc99** [comment]
May I try my hand at this?

**Comment by Yunusabdul38** [comment]
May I be assigned to this?
I have solid experience in both web2 and web3 and have contributed to open-source projects that ended up being merged
will be glad to work on this as my first contribution to this project
I will make sure to implement a pixel perfect UI with reference to the Figma design above

**Comment by anonfedora** [comment]
I am Eleazar, a fullstack blockchain developer, proficient in Cairo, Rust, Nextjs, Nestjs, I can handle this.

**Comment by ONEONUORA** [comment]
Could I try solving this? I am a full stack and blockchain developer. Good at creating pixel perfect features. ETA 24hours

**Comment by josephchimebuka** [comment]
Can I handle this ser... I will implement the leaderboard UI to fit the design this is my first time working on this project I will send a PR asap

**Comment by DioChuks** [comment]
I'd like to take this issue.

**Comment by Agbeleshe** [comment]
May I handle this issue? 
ETA :2days

**Comment by Ibinola** [comment]
Would love to tackle this!

**Comment by aurlic** [comment]
Hey I would love to be assigned to this issue. I am currently learning Cairo through Node Guardians, and have already worked on some Front End projects and I think that this would be a great match to further develop my skills. Thanks in advance !

**Comment by sonkiee** [comment]
Is this issue still available?
