### ISSUE TITLE
Player Components and Status UI

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#132]
### Description
Implement the player components for all corners of the game board, making the board the child component. Design with a board abstraction in mind, possibly using a square placeholder board skeleton component to have the board at mind for the UI, with the following features:

- [ ] Create pixel art avatar containers with proper scaling
- [ ] Implement player status indicators (turn status, score dots)
- [ ] Add "Your Turn" indicator with icon
- [ ] Style player names and numbers
- [ ] Implement hover states and active states

**Technical Requirements:**
- Use Tailwind CSS for styling
- Implement as a React component
- Ensure responsive scaling without overflow
---

**Comment by Jagadeeshftw** [comment]
I'd love to give this a go.

**Comment by greatest0falltime** [comment]
Is it okay if I take this?

**Comment by 1nonlypiece** [comment]
Can I attempt this issue?

**Comment by olisaagbafor** [comment]
I’d like to work on this.

**Comment by martinvibes** [comment]
May I pick this up?
I'm a frontend dev and would like to work on this

**Comment by vestor-dev** [comment]
Can I take care of this issue?
Please assign me

**Comment by emarc99** [comment]
Can I take this issue?
I have experience building FE projects using React, Next, tailwind and shadcn. I would love the opportunity to work on this awesome gaming project. Test e verything works as expected. ETA - 2 days max.

**Comment by josephchimebuka** [comment]
Can I handle this ser... I am good in frontend development and will complete this asap in 48 hrs

**Comment by Agbeleshe** [comment]
Can I handle this task?

**Comment by jahrulezfrancis** [comment]
This would be my first task with StarkLudo and I'd love to contribute to this issue. I’m confident in my ability to handle it effectively. My ETA for completion is 24 to 36 hours tops.

**Comment by Ibinola** [comment]
Can I attempt this issue?

**Comment by sonkiee** [comment]
Could I take on this issue?
