### ISSUE TITLE
Implement the `roll()` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#136]
- When the function is called, it should return a tuple with two random `u8` values within the range of 1 to 6 inclusive
- You can utilise Dojo's inbuilt random generator or [Pragma](https://docs.pragma.build/v1/Resources/randomness/randomness) to generate random the expected random values
- Also include unit test to verify the functionality of your code
- The function is located in the `game_actions.cairo` file
- The test should be located in the `test_game.cairo` file

**Comment by Birdmannn** [comment]
Please can I hop on this task. I'm Pascal, and I have experience in writing cairo-starknet smart contracts and I have worked with the Spotnet project, you can check my repo. I have gone through the codebase and my eta is 1 hour

**Comment by aurlic** [comment]
Hey I am currently learning Cairo through Node Guardians and I think that this issue would be a great match for me ! I would love to contribute to this project and improve my skills at thte same time and this seems like a really good option. Thanks in advance !

**Comment by Thibrac** [comment]
Je pense que je peux resoudre cette issue en m'aidant de la doc, ca me permettra de progresser, i'm lvl 8 on NodeGuardian :)

**Comment by emarc99** [comment]
I have sufficient cairo experience to handle. Let me do this please.

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the game_actions.cairo file to understand the current structure and identify where the function to return a tuple of random values needs to be implemented.
Implement the function to return a tuple with two random u8 values within the range of 1 to 6, using Dojo’s inbuilt random generator or Pragma to generate the values.
Ensure the function is correctly returning the expected random values within the given range.
Write unit tests in the test_game.cairo file to verify that the function correctly returns two random u8 values in the specified range.
Verify that the random values are consistently generated and fall within the correct range.
ET: 1 day

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d love to take on this issue! With strong experience in Cairo development and the StarkNet ecosystem, I can implement the roll() function to return a tuple with two random u8 values in the range of 1 to 6, utilizing Dojo’s inbuilt random generator or Pragma as required.

Additionally, I’ll write a thorough unit test in test_game.cairo to verify the correctness and expected behavior of the function. If approved, I’ll ensure to deliver a high-quality PR within the next 12-24 hours.

Looking forward to contributing! Let me know if I can proceed.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
Let me handle this issue!
ETA: 1 day

**Comment by OJDIT** [comment]
I’d like to resolve this.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
I’m interested in this one.

**Comment by GideonBature** [comment]
Can I take care of this issue?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, writing both the smart contract and integration test for the contract. If I am assigned, I will send my first PR within 24 hours.

Thank you!

**Comment by obacollins-lab** [comment]
Can I try solving this issue?

**Comment by Abeeujah** [comment]
Hi, I'm a smart contract developer, experienced in Rust, Cairo; I've worked on generating pseudo-random numbers a couple of time, and have good experience in this field as well, I'd narrow down the range in which the pseudo-random number should be generated from to `1>=n<=6`. I'd love to work on this and promise to deliver a great job if assigned.
