### ISSUE TITLE
Implement the `join()` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#137]
- The function should allow a player to join an existing game
- It should take the player's username, selected colour.
- A player should not be able to join a game when the max number of player has been reached
- Once the last player joins the game, the game starts automatically.
- Also include unit test to verify the functionality of your code
- The function is located in the `game_actions.cairo` file
- The test should be located in the `test_game.cairo` file

**Comment by vestor-dev** [comment]
I'd be happy to do this.
May I handle this issue?
i'm a blockchain dev and would love to work on this issue 
kindly assign :)

**Comment by Thibrac** [comment]
I'd love to continue making progress in Cairo alongside NG and other projects :)

**Comment by aurlic** [comment]
Hey I'm really interested in this issue ! I would love to be able to contribute and perfect and develop my skills in Cairo even more (I am curently learning through Node Guardians).

**Comment by emarc99** [comment]
Would love to tackle this!

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the game_actions.cairo file to understand the current structure and identify where the player join functionality needs to be implemented.

Implement the function to allow a player to join an existing game by taking their username and selected color.

Ensure that the function prevents joining if the maximum number of players has been reached.

Implement logic to start the game automatically when the last player joins.

Write unit tests in the test_game.cairo file to verify the functionality of the implemented code.

ET: 1 day

**Comment by Birdmannn** [comment]
can I handle this task? I'm Pascal Torti, an experienced cairo dev. I've handled card and board games in the past and I know very much about state management. Once in the function, I'll assert that the number of players in not equal to the max, and I'll make sure the game starts automatically when the last player joins. 


I shall also carry out tests to ensure what I have implemented is correct and bug free, without breaking any existing function.


ETA: 3 hours

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be excited to work on this issue! With extensive experience developing smart contracts using Cairo and testing them on StarkNet, I can implement the join() function to allow a player to join an existing game, ensuring:

The function accepts the player's username and selected color.
It prevents players from joining if the maximum number of players has been reached.
The game starts automatically once the last player joins.
I will also include comprehensive unit tests in test_game.cairo to verify the functionality and edge cases of the implementation. If approved, I’ll deliver a robust and high-quality PR within the next 12-24 hours.

Looking forward to your feedback!

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
Could I grab this task?
ETA: 1 day

**Comment by muheebyusufbaba1** [comment]
ill like to hop on this one 
worked on several issues on this project before now

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
May I handle this issue?

**Comment by GideonBature** [comment]
May I be assigned to this?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, writing both the smart contract and integration test for the contract. If I am assigned, I will send my first PR within 24 hours.

Thank you!

**Comment by obacollins-lab** [comment]
I’d like to work on this.
