### ISSUE TITLE
Implement the `start()` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#138]
- The function should be update the game status to `ONGOING`
- Also include unit test to verify the functionality of your code
- The function is located in the `game_actions.cairo` file
- The test should be located in the `test_game.cairo` file

**Comment by Thibrac** [comment]
I think I can solve this issue with the help of the docs, which will help me make progress :)

**Comment by aurlic** [comment]
Hey I'm really interested in this issue and think I could do a good job soving it. I am currently learning Cairo through Node Guardians and I can defientely tackle this issue to improve my skills in Cairo. Thanks in advance !

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the game_actions.cairo file to understand the current structure and identify where the game status needs to be updated.

Implement the function to update the game status to ONGOING.

Write unit tests in the test_game.cairo file to verify the functionality of the implemented code.

Ensure the function and tests are aligned with the existing contract logic and perform thorough testing to verify correctness.

ET: 1 day

**Comment by Birdmannn** [comment]
I'd love to hop on this task. I'll handle the assignment and carry out tests on it.

**Comment by emarc99** [comment]
I will study the codebase, implement the function and test appropriately. ETA 2 days.

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to take on this issue! With my experience developing smart contracts in Cairo and testing them on StarkNet, I can implement the start() function to update the game status to ONGOING.

I will also include a comprehensive unit test in test_game.cairo to verify the functionality and ensure it behaves as expected. If approved, I’ll deliver a clean and high-quality PR within the next 12-24 hours.

Looking forward to contributing—let me know if I can proceed!

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
I'd love to work on this!
ETA: 1 day

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
Could I grab this task?

**Comment by GideonBature** [comment]
Could I try solving this?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, writing both the smart contract and integration test for the contract. If I am assigned, I will send my first PR within 24 hours.

Thank you!

**Comment by obacollins-lab** [comment]
I’d like to work on this.

**Comment by Kingsuite** [comment]
May I pick this up?

**Comment by CollinsC1O** [comment]
Can I be assigned to this?

**Comment by ibsule** [comment]
Completed by #164
