### ISSUE TITLE
Update `dojo_dev.toml` with the current information

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#139]
- Some information in this file seems to be outdated
- Update the file with the current information about the game

If you need help with any information, you can ask in the [StarkLudo Contributors Telegram](https://t.me/+hnjQooODZOA2M2Rk)

**Comment by Thibrac** [comment]
I've finished the core common at ecole 42 and I want to work in this ecosystem, I'm making good progress on NG on the side so I think I can resolve this issue! :)

**Comment by emarc99** [comment]
Can I take care of this issue?

**Comment by ayush99336** [comment]
Can I be assigned for this issue it would be my first contribution in this project.

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the documentation in the file to identify outdated or incorrect information.

Update the file with the current information about the game, ensuring all details are accurate and up-to-date.

Cross-check the updated details with the latest features or functionality in the game, and if necessary, reach out to the StarkLudo Contributors Telegram for clarification on any information.

ET: 1 day

**Comment by emmz3230** [comment]
I'd love to give this a go.

hi 
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.
I got my first GitHub. badge by contributing to documentation sites and readme.

My questions are, what are the things that need to be updated?
Is it the installation process or project description?
will love to know

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to update the dojo_dev.toml file with the current information about the game. I will ensure all details are accurate and up-to-date. If I need clarification on any specific information, I’ll reach out in the StarkLudo Contributors Telegram group as suggested.

Once approved, I’ll deliver a clean and well-organized PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by OJDIT** [comment]
Could I take over this issue?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
Can I take care of this issue?

**Comment by GideonBature** [comment]
Mind if I take this issue?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I also write clear and detailed information about projects in the Readme. If assigned this task, will send my first PR in 24 hrs.

Thank you!

**Comment by obacollins-lab** [comment]
Could I take a shot at this?

**Comment by Kingsuite** [comment]
I’d like to work on this. It will be exicting to contribute to this project

**Comment by Birdmannn** [comment]
Can I take this task up?

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to update the dojo_dev.toml file with the current information about the game. I will ensure all details are accurate and up-to-date. If I need clarification on any specific information, I’ll reach out in the StarkLudo Contributors Telegram group as suggested.

Once approved, I’ll deliver a clean and well-organized PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by Birdmannn** [comment]
Please I’d like to resolve this.

**Comment by CHEF-SAVY** [comment]
Yo, I'm Isaac, a frontend dev.
I'd like to take on this issue.
ETA: 1day

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to update the dojo_dev.toml file with the current information about the game. I will ensure all details are accurate and up-to-date. If I need clarification on any specific information, I’ll reach out in the StarkLudo Contributors Telegram group as suggested.

Once approved, I’ll deliver a clean and well-organized PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.

ETA:
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
Let me try this one!
ETA: 1 day
