### ISSUE TITLE
Update `dojo_release().toml` with the current information

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#140]
- Some information in this file seems to be outdated
- Update the file with the current information about the game

If you need help with any information, you can ask in the [StarkLudo Contributors Telegram](https://t.me/+hnjQooODZOA2M2Rk)

**Comment by Birdmannn** [comment]
Hi dev. I'm an experienced cairo dev, and I would love to handle this task

**Comment by emarc99** [comment]
Can I contribute to this one?

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. 

ET: 1 day

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be glad to take on this task! I’ll update the dojo_release.toml file with the current and accurate information about the game. If I need clarification or further details, I’ll consult the StarkLudo Contributors Telegram group as suggested.

Once approved, I’ll ensure to deliver a clean and well-documented PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
I’d like to resolve this.
ETA: 1 day

**Comment by OJDIT** [comment]
Is it okay if I take this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects sunshine etc  .   please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
Is it okay if I take this?

**Comment by GideonBature** [comment]
I'd be happy to do this.

Mind if I take this issue?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I also write clear and detailed information about projects in the documentation and package file. If assigned this task, will send my first PR in 24 hrs.

Thank you!

**Comment by obacollins-lab** [comment]
May I pick this up?

**Comment by blessingbytes** [comment]
I would love to tackle this task

**Comment by vibenedict** [comment]
Closed by #156
