### ISSUE TITLE
Update book routes

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#141]
- [Scope](https://github.com/sivicstudio/starkludo/blob/dev/book/vocs.config.ts)
- use dash (-) to separate all route names in the book
- e.g ***/rollingdice*** should be update to ***/rolling-dice***

**Comment by Prosper1218** [comment]
can i work on this for you ? 
i would love to contribute to this project.
expect my PR within the next 12hrs.

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. 

ET: 1 day

**Comment by emarc99** [comment]
I’d like to help with this. Have done documentations in previous ODhacks that were merged.

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to work on this issue! I will update all book routes to use dashes (-) for separation, ensuring consistency (e.g., /rollingdice → /rolling-dice).

If approved, I’ll deliver a clean and well-tested PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by emmz3230** [comment]
Mind if I take this issue?
hi 
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

I would love to take on this issue by checking the path name in the folder or file directory and updating it in the page or app file.

Thanks, I really appreciate it if I am given the chance.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about less than 1 day. Let me know if I can get started!

**Comment by greatest0falltime** [comment]
Could I be assigned to this?
ETA: 1 day

**Comment by OJDIT** [comment]
I’d like to help with this.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer expert in Cairo , Rust and Solidity and also in web development.
please /assign this issue .
Thank You

**Comment by Yunusabdul38** [comment]
I’d like to work on this.

**Comment by Pvsaint** [comment]
I'd love to give this a go. I'm Victor, a front-end developer and I'd love to contribute to this project.

**Comment by GideonBature** [comment]
May I try my hand at this?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. If assigned this task, will send my first PR in 24 hrs.

Thank you!

**Comment by obacollins-lab** [comment]
I’d like to work on this.

**Comment by PedroCo3lho** [comment]
Hello @princeibs, can I work on it?
I'm a full-stack dev with a solid understanding of Typescript and React frameworks. I'd like to tackle this issue, will start by editing the routes in the `book/vocs.config.ts` file according to the new provided standards. Afterward, I’ll test the implementation throughout the application to ensure the changes meet the expected quality.
I’m looking forward to your approval so I can get start and delivery asap.

**Comment by aurlic** [comment]
I’d like to work on this.

**Comment by Michaelkingsdev** [comment]
Is it okay if I take this?

**Comment by SimplementeCao** [comment]
Hi I would like to work on this issue, I estimate about 6hs to finish it.

**Comment by ONEONUORA** [comment]
Can I handle this task?. I am fullstack and blockchain developer. ETA 24hours
