### ISSUE TITLE
Update `onchain` README with current information

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#143]
- The setup guide in the README of the `onchain` directory is currently outdated.
- Update the guide with the latest information

**Comment by FrankiePower** [comment]
I am Super Franky, a software developer with 3+ years of experience, and I have worked with frontend technologies like React, NextJS, JavaScript/TypeScript. I am also proficient in Cairo and Solidity for smart contract development. I'm a recent graduate of Web3bridge Africa, the foremost and premier blockchain developer community. I have made contributions to many open-source projects, and I look forward to contributing to this one. My approach to this will be to:

Review the documentation in the file to identify outdated or incorrect information.

Update the file with the current information about the game, ensuring all details are accurate and up-to-date.

Cross-check the updated details with the latest features or functionality in the game, and if necessary, reach out to the StarkLudo Contributors Telegram for clarification on any information.

ET: 1 day

**Comment by Joewizy** [comment]
I'd love to give this a go.

**Comment by emarc99** [comment]
Can I tackle this one?

**Comment by Birdmannn** [comment]
May I try my hand at this?

**Comment by Yunusabdul38** [comment]
I’d like to resolve this.

**Comment by jahrulezfrancis** [comment]
I'd love to contribute to this. I'll update the README in the onchain directory to include the latest setup instructions, ensuring it's clear and accurate for developers. The guide will reflect the current state of the project and tools. My ETA is 8 to 24 hours.

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to work on this issue! I will update the README in the onchain directory with the latest and accurate setup guide, ensuring it reflects the current state of the project.

If approved, I’ll deliver a clear, updated, and high-quality PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by emmz3230** [comment]
May I try my hand at this?

hi 
I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.
I got my first GitHub. badge by contributing to documentation sites and readme.

**Comment by ussyalfaks** [comment]
I'd be happy to help with this. I'll update the README in the onchain directory with the latest setup instructions to make sure it's clear and up to date for developers.

**Comment by greatest0falltime** [comment]
Can I work on this, please?  ETA: 1 day

**Comment by OJDIT** [comment]
I'd like to handle this task.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have already  make readme.md  for many projects
 please /assign  this issue .
Thank You

**Comment by Pvsaint** [comment]
May I handle this issue?
If it's still available,  eta 12hrs

**Comment by Naomi-Gift** [comment]
@princeibs I will be glad to work on this issue
I am a web3 developer/ Technical writer
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/commit/fc28412
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by GideonBature** [comment]
May I try my hand at this?

My name is Gideon Bature, a Software Engineer with experience writing TypeScript and Cairo. I will love to work on this issue, updating the setup guide in the README.md of the `onchain` directory with the latest information. If I am assigned, I will send my first PR within 48 hours.

Thank you!

**Comment by obacollins-lab** [comment]
I’d like to help with this.

**Comment by Kingsuite** [comment]
Can I start working on this? It will be nice to jump on this issue

**Comment by Michaelkingsdev** [comment]
May I try my hand at this?

**Comment by Birdmannn** [comment]
Can I tackle this one?

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to work on this issue! I will update the README in the onchain directory with the latest and accurate setup guide, ensuring it reflects the current state of the project.

If approved, I’ll deliver a clear, updated, and high-quality PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by Birdmannn** [comment]
Can I handler this?

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to work on this issue! I will update the README in the onchain directory with the latest and accurate setup guide, ensuring it reflects the current state of the project.

If approved, I’ll deliver a clear, updated, and high-quality PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by CHEF-SAVY** [comment]
Yo, I'm Isaac, a frontend dev.
I'd appreciate it if i can take on this issue.
ETA: 1day

**Comment by Jagadeeshftw** [comment]
Hello @princeibs,

I’d be happy to work on this issue! I will update the README in the onchain directory with the latest and accurate setup guide, ensuring it reflects the current state of the project.

If approved, I’ll deliver a clear, updated, and high-quality PR within the next 12-24 hours. Let me know if I can proceed!

Looking forward to contributing.

**Comment by 1nonlypiece** [comment]
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.

ETA:
I estimate completing this task in about less than 1 day. Let me know if I can get started!
