### ISSUE TITLE
Remove all log messages from client codebase

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#160]

**Comment by emarc99** [comment]
I'd like to handle this task. ETA 1 Day.

**Comment by ekumamatthew** [comment]
May I pick this up?

**Comment by Jagadeeshftw** [comment]
Could I grab this task?

**Comment by 1nonlypiece** [comment]
Can I contribute to this one?

**Comment by Ndifreke000** [comment]
Can I get this issue??

**Comment by kcmikee** [comment]
Hello, starkludo maintainers!!

I am a fullstack web developer and a recent alumnus of Web3Bridge, the largest and most sought after blockchain developer community in Africa. I have extensive frontend experience building beautiful frontend dashboards and mobile screens for e-commerce and education websites. I am a new contributor to OnlyDust and would love to take on this task to increase my knowledge base and contribute to open source projects.

I have experience in:

Frontend: HTML/CSS, JavaScript/TypeScript, Tailwind, Shadcn/UI, React.js, and Next.js
Backend: Node.js (Express.js)
Web3: Solidity and Rust.

I will tackle this issue using these steps:

1. Analyze the Figma Design: Review the Figma design and any relevant files.
2. Implementing the button, ensuring it adheres to the application's color scheme and branding.
3. Make sure it doesn't affect the application performance 

Estimated Time (ET): 1 day.

Thank you for the opportunity and I look forward to working with you. LET'S BUILD! 🚀
