### ISSUE TITLE
Document `namespace_def()` and `contract_defs()` 

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#161]
- Both functions are located in `test_game.cairo`
- You can get more explanation of the functions [here](https://book.dojoengine.org/framework/testing)

**Comment by Jagadeeshftw** [comment]
Could I be assigned to this?

**Comment by emarc99** [comment]
May I handle this issue?

**Comment by Pvsaint** [comment]
May I work on this issue please, I'm a frontend and smart contract developer and I'll love to contribute to this project

**Comment by 1nonlypiece** [comment]
I’m interested in this one.

**Comment by ekumamatthew** [comment]
I'd like to take this issue.
