### ISSUE TITLE
Add telegram link to game book

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#162]

**Comment by emarc99** [comment]
Could I try solving this?

**Comment by omsant02** [comment]
I would like to take this issue @princeibs 
ETA :6 HRS

**Comment by ryzen-xp** [comment]
Hi Sir , I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by ekumamatthew** [comment]
May I take this issue on?

**Comment by sonkiee** [comment]
May I be assigned to this?

**Comment by 3th-Enjay** [comment]
I'd love to give this a go.

**Comment by Yunusabdul38** [comment]
May I handle this issue?

**Comment by jaykayudo** [comment]
Can I take this from here?

**Comment by RomThpt** [comment]
Mind if I take this issue?

**Comment by Annieodes** [comment]
Is it okay if I take this?

**Comment by Annieodes** [comment]
i'd love to work on this task!
i can add the telegram link
