### ISSUE TITLE
Redesign the control and game status page

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#30]
Currently the game control page does not give much details/guide to players (especially new players) at first glance of the game. The game status page also does not give much details/guide as well. Redesign both pages on Figma to give more details/guide to the players.

**Note: This issue requires that the project leads gives more context via call.**

---
If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a product designer

### How I plan on tackling this issue
I can handle this

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi, I am an experienced Ui/Ux designer and a blockchain developer. I would love to work on this as soon as possible please

### How I plan on tackling this issue
1. I'll make sure to come up with a user centric design that matches with the brands colours
2. I'll make sure to highlight the CTA
3. I'll make sure to add subtle/micro interactions/animations
4. I'll ad enough details/guide to new players AT FIRST GLANCE

Please assign this issue to me, I am ready to work.
ETA: 2 days max

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
cani

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
can i

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have experience in frontend development and UI/UX design, with a strong focus on creating user-friendly interfaces. My expertise lies in simplifying complex user flows and ensuring intuitive navigation for both new and returning users. This background equips me to redesign the game control and status pages to be more informative and accessible, especially for first-time players.

### How I plan on tackling this issue
I’d start by discussing with the project leads to fully understand user pain points. Then, I’d analyze the existing pages and identify areas of confusion. My approach involves creating user personas, wireframing enhanced layouts on Figma with clear instructions and visual guides, and iterating based on user feedback. The goal is to balance clarity with simplicity, ensuring players receive all necessary guidance without cluttering the interface.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a product designer with experience

### How I plan on tackling this issue
Understand Requirements:

Contact project leads to gather detailed context about the game control and game status pages.
Join the StarkLudo contributors channel on Telegram for additional support and information.
Analyze Current Design:

Review the existing game control and game status pages to identify areas lacking detail or guidance.
Redesign in Figma:

Create a more detailed and user-friendly design for both pages in Figma.
Ensure the new design includes clear instructions and guidance for new players.
Review and Feedback:

Share the redesigned pages with project leads and other contributors for feedback.
Iterate on the design based on feedback received.
Implement Changes:

Once the redesign is finalized, coordinate with the development team to implement the new designs.
Test and Validate:

Test the redesigned pages to ensure they effectively guide players and improve user experience.

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
