### ISSUE TITLE
Create logic for `terminate_game` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#41]
**Description**

The logic is expected to terminate an ongoing game. It should make the following modifications to a game state:
- set `game_state` to `Ended`
- Evaluate the winner (if there is any)
- Add the game to the list of games the player has played

**Test**
Create unit test for this particular function to verify the correctness of the logic implemented

**File(s) to modify:**
- `game_actions.cairo`

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
@princeibs I'd love to work on this. I'm a Cairo developer

### How I plan on tackling this issue
I'd follow the procedures outlined in the issue to tackle this problem

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
l'm a front end and also a smart contract developer. I will love to work on this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a block chain dev and would love to work on this

### How I plan on tackling this issue
### Steps to Solve
#### Implement terminate_game Function:

- In the game_actions.cairo file, create the terminate_game function.
Set game_state to Ended: Modify the game state to indicate that the game has ended.

- Evaluate the Winner: Determine if there is a winner and update the game state accordingly.
Record Game: Add the completed game to the player's history of played games.
Write Unit Tests:

**Create unit tests to validate the functionality of the terminate_game function, ensuring that it correctly ends the game, evaluates the winner, and records the game.
Open a Pull Request:**

Once completed, open a pull request to the relevant branch with your implementation and tests.

**Comment by GoSTEAN** [comment]
I am applying  via  [OnlyDust Platform](https://www.onlydust.com/)

I am a frontend developer and smart contract developer

**Comment by ibsule** [comment]
Hi @EjembiEmmanuel, any progress on this?

**Comment by EjembiEmmanuel** [comment]
@princeibs I apologize for the delay. I'd create a PR today
