### ISSUE TITLE
Create logic for `update_username` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#42]
**Description**

The function is expected to take in a new username and update a player's username
- Only a player can update their username
- They can only update to a username that has not been claimed by another player

**Test**
Create unit test for this particular function to verify the correctness of the logic implemented

**File(s) to modify:**
- `player_actions.cairo`

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs, I am Ikem Peter a fullstack developer and I have contributed to 4 different projects through Onlydust.

I would like to take on this issue.

ETA: 4hrs

### How I plan on tackling this issue
- map user address to name
- only address can modify name 
- check if name already maps to an address before allowing usage.

**Comment by muheebyusufbaba1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a full stack developer.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
l'm a front end and also a smart contract developer. I will love to work on this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a block chain dev and i would love to work on this

### How I plan on tackling this issue
### Steps to Solve
#### Implement update_username Function:

`In the player_actions.cairo file, create the update_username function.`

**Accept New Username:** The function should take the new username as an input.

**Verify Player Identity:** Ensure that only the player attempting to change the username is allowed to do so.

**Check Username Availability**: Verify that the new username is not already claimed by another player.

**Update Username:** If the above conditions are met, update the player's username.

### Write Unit Tests:

Create unit tests to validate the functionality of the update_username function. Tests should cover scenarios where the update is successful, where the username is already taken, and where someone other than the player tries to update the username.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a blockchain developer and i would love to take this up

### How I plan on tackling this issue
Implement update_username:

Language: Cairo
Modify: player_actions.cairo
Functionality: Update a player’s username if it’s not taken and the request is made by the player.
Create Unit Tests:

Language: TypeScript
Task: Test the function to ensure:
Only the player can update their own username.
The new username is unique.
Handle errors and invalid requests.
Run Tests:

Verify the function with the unit tests to ensure correctness.
Submit Pull Request:

Include the updated code and tests in a pull request for review.

**Comment by NueloSE** [comment]
@princeibs can I work on this

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
am a developer with experience using frontend technologies and writing smart contract i would be able to handle this task if assigned

### How I plan on tackling this issue
Function Implementation:

Objective: Create a function that updates a player's username.
Conditions:
The function should accept a new username as input.
It should check if the username is already taken by another player.
Only the player themselves can update their username.
If the new username is available, update the player's username.
Unit Test:

Purpose: Verify that the function works correctly.
Test Cases:
Attempt to update to a new, available username and verify success.
Attempt to update to a username that is already taken by another player and verify that the update is rejected.
Attempt to update the username from a player other than the one currently logged in, ensuring it is blocked.
