### ISSUE TITLE
Create logic for `restart_game` function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#44]
**Description**

The logic is expected to reset the game logic to the initial state of the game when it first started.

**Test**
Create unit test for this particular function to verify the correctness of the logic implemented

**File(s) to modify:**
- `game_actions.cairo`

**Comment by CollinsC1O** [comment]
Hello @princeibs love to work on this

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Am a frontend dev with experience in frontend development and smart contract development. I have used cairo and rust programming languages before and i know i can handle this task

### How I plan on tackling this issue
1. create the reset_game_logic function 
2. create a unit test suit to test the state before and after function implementation

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
l'm a front end and also a smart contract developer. I will love to work on this

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a blockcchain dev i would love to take this

### How I plan on tackling this issue
Issue Overview
Goal: Implement a restart_game function.
Functionality: Reset the game to its initial state.
File to Modify: game_actions.cairo
Testing: Create unit tests to validate the correctness of the restart_game function.

### Steps to Solve
- Implement the restart_game function in the game_actions.cairo file to reset all game-related variables and states to their default or initial values.
- Write unit tests to check that the game resets correctly and behaves as expected when the restart_game function is called.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer with extensive experience in React.js ,Cairo, Rust and TypeScript to build dynamic and responsive user interfaces. My background in these technologies allows me to create seamless and efficient web applications, focusing on delivering a user-friendly experience. By combining my technical skills with a strong understanding of modern development practices, I am well-equipped to contribute to any project, ensuring that the final product is both high-performing and intuitive for end-users.

### How I plan on tackling this issue
1. Reset Game Logic:
Implement a function in the game_actions.cairo file that resets the game state to its initial condition, as it was when the game first started.
This function should ensure that all game variables, player states, and other relevant data are reset.
2. Unit Test:
Create a unit test for this reset function to ensure it behaves as expected.
The test should:
Set up an initial game state (possibly non-default).
Call the reset function.
Verify that the game state matches the expected initial conditions after the reset.

3. Files to Modify:
The main file to work on is game_actions.cairo, where you'll both implement the reset logic and write the corresponding unit test.
Steps to Follow:Define the Reset Function:

Identify what constitutes the "initial state" of the game.
Write the function to reset all necessary variables to this state.
