### ISSUE TITLE
Test game rules implementation 

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#45]
Currently, the game play is guided by some set of pre-defined rules. These rules define how the game components interact with each other as well as the actions the components can execute.

These rules have been hard-coded into the logic of the game as works as expected, but it has not been tested thoroughly to verify all rules are implemented correctly.

The task here is to study and understand all the game rules and then play the game from beginning to the end to confirm if all the rules have been implemented correctly. 

When the task is done, open a pull request to the `dev` branch with a `.md` file describing the findings from your test.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a block chain developer i would love to take this

### How I plan on tackling this issue
### Steps to Solve
Study the Game Rules:

1. Review all the pre-defined rules that guide the gameplay.
Understand how these rules dictate the interaction between game components and the actions they can execute.
Play the Game:

2. Play the game from the beginning to the end.
Carefully observe whether each rule is correctly implemented and how it affects gameplay.
Take notes on any discrepancies, issues, or rules that seem to be missing or incorrectly applied.
Document Findings:

3. Create a .md file (Markdown) summarizing your observations.
List any rules that were correctly implemented as well as those that were not.
Provide a detailed description of any issues encountered.
Open a Pull Request:

**Comment by Ayoazeez26** [comment]
@princeibs Can I work on this?

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
l'm a front end and also a smart contract developer. I will love to work on this

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects.

### How I plan on tackling this issue
I am very familiar with the traditional Ludo game, I will study the game rules and play the game end to end to confirm that all the rules have been implemented correctly and the work as expected

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
a

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
am a frontend develooper with expirence in testing web application and have expirence writing test for smart contract

### How I plan on tackling this issue
1. I would study and Understand Game Rules:
Review and fully understand the rules that govern the gameplay. These rules have been hard-coded into the game's logic.
2.  I would Play the Game from Start to Finish:
Play the game from the beginning to the end to verify if all the rules are implemented correctly.
Observe the interactions and actions of the game components to ensure they align with the defined rules.
3. Document my Findings:
After completing the testing, document your findings in a .md file. This file should include:
A summary of the rules tested.
Any discrepancies or issues found.
Confirmation if all rules are correctly implemented.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer with extensive experience in React.js ,Cairo, Rust and TypeScript to build dynamic and responsive user interfaces. My background in these technologies allows me to create seamless and efficient web applications, focusing on delivering a user-friendly experience. By combining my technical skills with a strong understanding of modern development practices, I am well-equipped to contribute to any project, ensuring that the final product is both high-performing and intuitive for end-users.  

### How I plan on tackling this issue
To tackle the task of verifying the implementation of game rules and documenting your findings, follow these steps:

1. Understand the Game Rules
Obtain the Rules Document: Acquire any documentation or specifications that detail the game's rules and mechanics.
Review the Rules: Thoroughly read and understand each rule. Identify how these rules impact the interactions between game components and the actions available within the game.
2. Set Up the Testing Environment
Prepare the Game: Ensure the game is in a state where it can be tested. This might involve setting up the development environment, ensuring all dependencies are installed, and the game is running correctly.
Create Test Accounts or Profiles: If necessary, set up test accounts or profiles that allow you to test different scenarios without affecting real user data.
3. Play Through the Game
Plan Your Testing: Develop a plan for how you will play through the game to cover all possible scenarios. This includes various stages, interactions, and actions defined by the rules.
Play the Game: Start playing the game from beginning to end, carefully following each rule and noting how the game behaves. Pay attention to both common and edge cases.
Document Issues: As you encounter any discrepancies or issues with the rules not being followed, make detailed notes.
4. Verify Each Rule
Cross-Reference: As you test, cross-reference each action and interaction with the documented rules to ensure compliance.
Check Edge Cases: Ensure that rules are implemented correctly in edge cases or unusual scenarios that may not be covered by normal gameplay.
5. Compile Findings
Document Your Findings: Create a .md file to summarize your testing process and results. Include:
Overview: A brief description of the game and the purpose of your testing.
Testing Methodology: How you approached the testing (e.g., scenarios tested, any specific focus).
Findings: A detailed list of findings, including:
Confirmed Rules: Rules that are correctly implemented.
Issues: Any discrepancies or issues found, including steps to reproduce, if possible.
Suggestions: Any suggestions for improving rule implementation or addressing found issues.
6. Open a Pull Request
Create the .md File: Ensure the .md file is properly formatted and contains all necessary information.
Commit Changes: Add the .md file to your local repository, commit the changes with a meaningful message.
Push to Remote: Push the changes to your remote branch.
Open a Pull Request: Navigate to your repository's pull request page, open a new pull request to the dev branch, and provide a clear description of what the pull request contains.
7. Review and Follow Up
Monitor the Pull Request: Check for any feedback or questions from your team and respond accordingly.
Address Feedback: If there are any requested changes or additional information needed, make the necessary updates and resubmit.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a web3 developer and i want to contribute to this

### How I plan on tackling this issue
Understand the Rules:

Review the pre-defined game rules and how they should guide interactions and actions within the game.
Study the Code:

Examine the current implementation of the game rules in the codebase. Look into the logic where these rules are hard-coded.
Play the Game:

Start the game from the beginning and play through to the end.
Observe how the rules are applied and check if the game behaves as expected according to the rules.
Test Thoroughly:

Test various scenarios and edge cases to ensure all rules are enforced correctly.
Take note of any discrepancies or issues where the rules are not implemented as expected.
Document Findings:

Create a .md file documenting your findings, including:
A summary of the rules tested.
Details of any discrepancies or issues encountered.
Suggestions for any fixes or improvements if applicable.
Open a Pull Request:

Submit a pull request to the dev branch with the .md file attached, summarizing your testing process and findings.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a professional QA Manual Tester, I work as a freelance Tester at uTest

### How I plan on tackling this issue
I will go through the following steps:
Gather Documentation: First, I would collect and review all available documentation related to the game's rules. This could include design documents, code comments, or any other sources that outline how the game is supposed to function.
Identify Key Rules: I would create a list of all the key rules that govern the game, categorizing them based on components, interactions, and actions.

**Comment by MatiasAchucarro** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a passionate and results-driven web developer, currently deepening my knowledge in web3 technologies, Cairo, and open-source development through Dojo Coding. My skill set includes expertise in JavaScript, React, HTML, CSS, C# with .NET Entity Framework, and more. I also have experience with tools like Git, GitHub, SQL Server, and Postman. My focus has been on building solid web applications, from task lists to full-fledged CRUD systems, with front-end, back-end, and database integration.

This will be my first contribution to the open-source ecosystem, and I am excited to learn and collaborate on innovative projects, particularly those involving Cairo.

### How I plan on tackling this issue
First, I would review the game documentation and code to thoroughly understand the rules. Then, I would play through the entire game to see if all the rules work as expected, taking note of any errors or strange behavior. Finally, I would create a .md file with my observations and open a Pull Request to the development branch, describing any issues found and attaching the file with the details.
