### ISSUE TITLE
Disable board until number of players have been selected

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#71]
**Description**
Currently, the Ludo board can still be interacted with even before the number of players for the game has not been selected.

**Action items**
- Disable and blur our the Ludo board until the number of players have been selected.
- Add an indication directing where the number of players will be selected.
- Use the image below as a guide: 
![image](https://github.com/user-attachments/assets/5adca83b-10b2-4bad-add9-b2f130981a8a)

**Comment by Iwueseiter** [comment]
Hi @princeibs please can I work on this?

I'm a frontend and smart contract developer. I've contributed to Projects here on onlydust
 and with that experience, I would handle this task as expected. This would also be my first time
contributing to this project.

**Comment by ShantelPeters** [comment]
Hi @princeibs please can I work on this issue ?

**Comment by CollinsC1O** [comment]
hello @princeibs can i work on this

**Comment by melnikga** [comment]
Hi, can I take this?

**Comment by martinvibes** [comment]
Hello @princeibs can I be assigned this issues

**Comment by Joy-Adah** [comment]
Hi @princeibs can I be assigned this? I'd love to work on it

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend developer and also a blockchain developer and I will love to work on this please

### How I plan on tackling this issue
- I will add state 'variable' to track if the number of players has been selected
- I will use conditional rendering or CSS to blur/disable the board if 'variable' is false
- I will apply a CSS class such as blurred to the board to blur and reduce pointer events while the board is disabled
- I will add a message or UI element prompting users to select the number of players, and make it visible until players are then selected
- To enable board once players are selected, I will update the state 'variable = true' to remove the blur and enable board interaction.
Thanks

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community


### How I plan on tackling this issue
Disable and blur our the Ludo board until the number of players have been selected.
Add an indication directing where the number of players will be selected.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a blockchain developer with experience in the field of UI/UX. this would be my first time contributing to this ecosystem . i am ready and avaliable to work.

### How I plan on tackling this issue
Below is how i intend to approach the problem:

1. I Will Disable Board Interaction
   - Implement a state that disables interactions with the Ludo board until the player count is selected.
2. Apply Blur Effect To It
   - Add a CSS class to blur the Ludo board when it’s disabled, indicating it’s not active.
3.  I will add a Player Selection Indicator:
   - Include a visual cue (like an arrow or highlight) to guide users to the player selection area.
4.  By using the provided Image as Reference:
   - Refer to the provided image for design consistency and layout.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I will address this issue by implementing the following changes:

1. Update the main App component to include state management for player selection:
   - Add a `playersSelected` state to track whether players have been chosen
   - Add a `numberOfPlayers` state to store the selected number of players

2. Create a new PlayerSelection component:
   - Include buttons for 2, 3, and 4 players
   - Add a "GO" button that becomes active only after player count is selected

3. Modify the Ludo component:
   - Add a `disabled` prop to prevent interactions when players aren't selected
   - Implement a blur effect when in the disabled state

4. Add an overlay to the Ludo board when players haven't been selected:
   - Display the message "Choose your number of players first to begin"
   - Include an animated arrow pointing towards the player selection area

5. Update the CSS to:
   - Style the new PlayerSelection component
   - Implement the blur effect on the Ludo board
   - Style the overlay and animated arrow

6. Ensure the layout matches the provided design, with the Ludo board on the left and controls on the right

7. Test the implementation to ensure:
   - The Ludo board is blurred and non-interactive until players are selected
   - The player selection UI is clear and easy to use
   - The GO button only becomes active after selecting the number of players
   - The overall layout and design closely match the provided image

I'll submit a PR with these changes once implemented for review.

ETA - 2 days

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a solid background in front-end development, particularly in JavaScript and TypeScript, as well as building interactive user interfaces using frameworks like React. I have worked on numerous projects where I needed to manage component states and interactions based on user inputs, such as disabling certain elements or showing specific UI prompts based on a condition. My experience in UI/UX ensures that I can implement intuitive user flows, such as disabling parts of the UI until required actions are completed.

This background will allow me to easily implement the functionality needed for this task by controlling the game board's interactivity, ensuring a clear visual indication of the necessary steps (like selecting the number of players), and maintaining a seamless user experience.



### How I plan on tackling this issue
To disable the Ludo board until the number of players is selected, I would approach the problem with the following steps:

Manage state for player selection: I would introduce a piece of state (e.g., numPlayersSelected) to track whether the number of players has been selected. This can be done with React’s useState hook or an appropriate state management tool, depending on how the project is structured.

Disable and blur the board: I would set the Ludo board component to be disabled by default, applying a CSS blur effect (e.g., filter: blur(4px)) and a pointer event block (pointer-events: none) to prevent user interaction with the board until the numPlayersSelected state has a valid value. When the state updates with the selected number of players, the board would return to its normal state.

Add visual cues for user guidance: To guide users on selecting the number of players, I would add a visual indication (like a message, icon, or tooltip) that clearly directs them to the player selection section. This indication would disappear once the number of players has been selected, and the board is activated.

Test the flow: After implementing the disabling and enabling mechanism, I would thoroughly test the user flow to ensure that the board remains disabled until the number of players is selected and that the blur effect and visual cues behave as expected. I would also ensure that the UI remains responsive and intuitive across different devices.

**Comment by SudiptaPaul-31** [comment]
Hey @princeibs I'm applying to this issue
I'm , a full-stack developer with experience in working with various web technologies, including React, Node.js, MongoDB, and cloud services like Google Cloud and Cloudinary. I'm excited to contribute to this project and would love to take on this issue.

Detailed Approach:
Disabling and Blurring the Ludo Board:

I'll add a conditional state in the application to check if the number of players has been selected.
Until this condition is met, I'll use CSS properties like pointer-events: none to disable interaction and apply a blur effect using filter: blur() to the Ludo board.
This will make the board visually inactive and non-interactive until the user selects the number of players.
Indication for Player Selection:

I'll place a prominent, intuitive indication in the UI directing users to select the number of players. This could be achieved by adding a pop-up or highlighting the player selection area using CSS animations (e.g., glowing borders or pulsating effects).
Tooltips or helper text will further guide the user to complete the player selection.
Testing and Optimization:

After implementation, I'll thoroughly test the functionality across different screen sizes and ensure accessibility for users with disabilities.

Looking forward to contributing and hope to hear from you soon!

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a frontend and smart contract developer. I've contributed to Projects here on onlydust
 and with that experience, I would handle this task as expected. This would also be my first time
contributing to this project.

### How I plan on tackling this issue
1. Conditional Rendering:
In the game logic, i will check if the number of players has been selected (e.g., store this state in a variable like playersSelected).
Conditionally render the Ludo board's interaction or use a CSS class to disable interaction and apply a blur effect if the players have not been selected.
2. Add an Indication for Player Selection:
I will provide a visual cue, such as an arrow or highlight, directing the user to where they need to select the number of players.
3. Handle Player Selection Logic:
I will create a UI section to select the number of players, and once the user selects it, update the playersSelected state to enable the board and remove the blur.

**Comment by aji70** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i am a react and smart contract developer and my skills will be just right for this

### How I plan on tackling this issue
will create a modal bluring the main cmponent behind and and if only when the condition is satisfies ie number of players have been selected will the main component be visible

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Fullstack developer 

### How I plan on tackling this issue
I'll ensure that the board cannot be interacted with,until the total number of players have been selected

**Comment by Agbeleshe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full stack developer with 3 years experience in HTML, CSS JavaScript, node.js React, Typescript and other libraries and frameworks .


### How I plan on tackling this issue
i will love this to be my first contribution to the community. 
First off i create a logic using conditional statement that checks the value of the Payers and if they are below the required length i disable the board using the appropriate style pattern sample. And for the indicator i will set the input field for the player to have a red boarder to indicate to players what's causing the issue if the conditions are met

**Comment by tumutech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i have advanced understanding of javascript, css and html and react which will be helpful to achieve the desired design.

### How I plan on tackling this issue
I will start by writing a script that checks number of players, if its null, it means non has been selected, therefore, i modify the style of the board div by disabling and adding a blur effect to it with an overlay of a text with a arrow guiding the user to choose the number of player

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Add a blur overlay on the board and display the component that allows users to select number of players

Make sure the implementation is functional and responsive across web browsers

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi I am a blockchain developer with 3 years experience. Previously contributed to this project and would love to contribute again.

### How I plan on tackling this issue
Allow an onblur css property, that can now be  used within the application. Further more , create a component to properly show where the number of players will be selected

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Can I take this? I’ve participated in almost every ODHack, and I already contributed to the StarkLudo project at the last hackathon. I have extensive experience in frontend development. I can handle this task.

### How I plan on tackling this issue
My profile on OD: https://app.onlydust.com/u/melnikga

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm Benjamin, a full-stack JavaScript developer, and I'm eager to improve the Ludo game experience by disabling the board until the number of players is selected. With my experience in building user-friendly interfaces, including 18 contributions to OnlyDust, I understand the importance of clear interactions in games.

### How I plan on tackling this issue
I will begin by implementing a feature that disables and blurs the Ludo board until the players are chosen. This will prevent any accidental interactions and create a smoother game setup process.

To guide users, I’ll add a clear indication of where they need to select the number of players. This could be a highlighted area or an arrow that draws attention to the selection feature, ensuring players know exactly where to click.

After making these changes, I’ll test the functionality to ensure that the board remains unresponsive until the necessary player count is set, providing a better user experience. My goal is to make the game more intuitive, allowing players to focus on the setup before diving into the gameplay.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have experience in UI/UX development and game logic implementation, which allows me to handle dynamic elements in games. I’ve worked on projects where game components are conditionally enabled or disabled based on user actions, ensuring smooth gameplay flow. My expertise in using CSS for visual effects (like blurring) and managing state logic will be valuable in implementing this feature efficiently.


### How I plan on tackling this issue
I would begin by disabling interactions with the Ludo board until the number of players is selected. This can be achieved by adding conditional logic to check if the number of players has been chosen and applying a blur effect via CSS to visually indicate the disabled state. I would also add a clear and prominent indication for the user to select the number of players, following the design guide provided. Finally, I’d test to ensure that the board becomes active and responsive only after a valid player selection is made.

**Comment by Rayan9064** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack Developer and Cairo Developer. I have good experience building web application. I am new to Open Source and want to begin with this project. I am good in React, Typescript, Redux and Context APIs. I can leverage the same to make this a better game for the users. 

### How I plan on tackling this issue
1) Checking the structure of the project and understanding the codebase. 
2) Knowing the tech stack required
3) Finding the area of the problem. 
3) Designing the Figma solution. 
4) Implementing into code. 
5) Testing the code by inspecting in different screen size. 
6) Modify the code when not working as expected. 
7) After successful review, create a pull request.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
**UI: Disable Ludo Board Until Player Selection**

Hello Starkludoteam,

I am **Joel Vargas**, a member of **Dojo Coding**, and I also come from **OnlyDust**. I have experience working with React, SCSS, and Tailwind, and I specialize in creating interactive UIs and controlling user flows based on conditions. My work in open-source contributions has involved similar tasks, such as disabling UI components until certain criteria are met.

I would like to request the assignment of the issue related to disabling the Ludo board until the number of players is selected. Below is my proposed approach for solving this issue.

### How I plan on tackling this issue
### **Implementation Plan**

**STEP 1: Disable and Blur the Ludo Board**

- I will disable interaction with the Ludo board by adding a conditional `disabled` state. Using Tailwind's `opacity-50` class, I will blur or fade out the board to visually indicate that it is inactive until the player count is selected.
- I will use a combination of `pointer-events-none` and `opacity` classes to prevent the board from being interacted with.
- A conditional rendering strategy will ensure that the board becomes active after the players are selected.

**STEP 2: Add Indication for Player Selection**

- I will create a clear visual indication (such as a prompt or overlay) directing users to select the number of players. This will involve a button or an input field where users can make their selection.
- I will place this prompt in a noticeable area, possibly above or near the board, to ensure clarity. The message will be styled using Tailwind classes like `text-xl`, `text-center`, and `text-blue-500` to stand out.

**STEP 3: Trigger Activation of the Ludo Board**

- After the number of players is selected, I will trigger a state change that enables interaction with the Ludo board by removing the `disabled` state and opacity filter.
- This will involve a simple check within the component state, possibly using `useState` or `useReducer` hooks in React to manage the logic of enabling/disabling the board based on the selection.

**STEP 4: Test and Validate the Flow**

- I will ensure that the interaction flow is smooth, i.e., the board is disabled at the start and only becomes available after the player count is confirmed.
- I'll perform thorough testing across various screen sizes and devices to ensure everything works as expected.

---

### Technical Stack

- **React**: For managing state and conditionally enabling/disabling the board based on user input.
- **SCSS & Tailwind CSS**: For handling the styles, including blurring and disabling the board as well as making the player selection prompt prominent.
- **React Hooks (useState)**: To manage the state for tracking whether the number of players has been selected.

---

### Example Code Outline

```jsx
export default function LudoBoard() {
  const [playersSelected, setPlayersSelected] = useState(false);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center">
      {/* Player Selection Prompt */}
      {!playersSelected && (
        <div className="mb-4">
          <p className="text-xl text-blue-500 text-center">Select the number of players to start the game</p>
          <button 
            className="bg-blue-500 text-white px-4 py-2 rounded"
            onClick={() => setPlayersSelected(true)}
          >
            Select Players
          </button>
        </div>
      )}

      {/* Ludo Board */}
      <div 
        className={`ludo-board ${playersSelected ? 'opacity-100 pointer-events-auto' : 'opacity-50 pointer-events-none'}`}
      >
        {/* Board content here */}
      </div>
    </div>
  );
}

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
Step 1: Add Selection Mechanism
Create a dropdown or button group to select the number of players
Populate options with possible player counts (e.g., 2-4)
Step 2: Disable Board Initially
Set the board's initial state to disabled:
Add disabled attribute to board elements (e.g., buttons, tiles)
Use CSS to gray out or opacity the board
Step 3: Enable Board on Selection
Attach event listener to player count selection:
Update board state to enabled when selection is made
Remove disabled attribute from board elements
Update CSS to restore board opacity and color

**Comment by Pvsaint** [comment]
Hi @princeibs I believe that with my 3 years react experience I can handle this issue if assigned to me.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged

hello i am a `frontend dev` and `blockchain developer`
please can i work on this issue :) kindly assign @princeibs

### How I plan on tackling this issue
### i would solve this issue by:

**Disable and Blur the Ludo Board:**
 - Prevent interaction with the board by disabling it and applying a blur effect until the number of players has been chosen.

**Add an Indication:**
- Provide a clear message or visual cue directing the user to select the number of players.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged

hello please can i work on this issue :) and would love to be a contributor


### How I plan on tackling this issue

Task: Disable Ludo Board Until Players Are Selected
Overview
The goal is to ensure that the Ludo board is not interactable until the player count is selected. Additionally, we’ll provide a visual indication directing users to the player selection area.

Steps to Implement
Disable Board Interaction:

Modify the board component to conditionally disable user interactions based on the player count selection.
Blur Effect:

Apply a CSS blur effect to the board when it’s disabled to visually indicate that it is not currently usable.
Add Player Selection Indication:

Include a clear indication or prompt near the player selection area to guide users on what to do next.
