### ISSUE TITLE
Make page fit 100% of screen

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#72]
**Description**
Currently, the page does not fit 100% of the screen. Players have to scroll down to see the other parts of the page.

**Action items**
- Make page fit 100% of the screen it is view from.
- Take note of the warning banner at the top. The page should still fit 100% even when the banner is removed
![image](https://github.com/user-attachments/assets/34077605-ce6e-401e-bcc2-f620ca44f1d1)

**Comment by od-hunter** [comment]
Hi @princeibs , please can I be assigned this? I’m ready to work.🙏🏾

**Comment by ShantelPeters** [comment]
Hello @princeibs 
Can i please be assigned to this issue ,this would be my first time contributing to this ecosystem

**Comment by CollinsC1O** [comment]
@princeibs I'm a frontend and also a blockchain developer. I will love to work on this, I'm very ready to work

**Comment by martinvibes** [comment]
@princeibs please let me work on this

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum exosystem.

### How I plan on tackling this issue
I will solve this issue by implementing the following changes:

1. Modify the CSS to use the layout for the entire page, ensuring 100% height utilization.
2. Position the warning banner absolutely at the top of the page to prevent it from affecting the main layout.
3. Restructure the main content into two flex containers: one for the Ludo board and one for the sidebar.
4. Implement overflow scrolling within each container to handle content that exceeds the viewport height.
5. Adjust the layout for mobile devices to stack vertically, with each section taking 50% of the screen height.
6. Update the React component structure to accommodate these layout changes.

These modifications will ensure the page fits 100% of the screen on both desktop and mobile devices, with or without the warning banner present. I'll submit a PR with these changes for review once implemented.

ETA - 1 day

**Comment by PabloVillaplana** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack developer with 6 years of experience in the industry, I am super excited to be able to contribute to Web 3 projects, this to continue paving my way as an Open Source Contributor. I am from Dojo Coding Community

### How I plan on tackling this issue
Check CSS for Full Screen Fit: Ensure the page layout is set to occupy 100% of the screen height, without needing scrolling.
Adjust for Banner Removal: Make sure the page dynamically adjusts when the top banner is removed, filling the available screen space.
Check for Overflow: Identify and fix any elements causing unintended overflow that leads to scrolling.
Test Responsiveness: Verify that the page adapts correctly across different screen sizes and devices.
Ensure Cross-Browser Compatibility: Test the page in multiple browsers to confirm consistent behavior.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js,  Rust and Cairo, I've honed my technical skills across the blockchain development landscape.

My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.

My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.

Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Approach for Ensuring the Page Fits 100% of the Screen:

I will begin by analyzing the current layout:
I will inspect the current page layout and identify the elements causing the page to exceed the screen height.
This will involve checking for unnecessary margins, paddings, and any elements that could cause the overflow issue.

I will adjust the CSS for full-screen fit:
I will modify the existing CSS to ensure that the page content fits 100% of the viewport height (vh), without causing scrolling.
This will involve using CSS properties like height: 100vh or min-height: 100vh to make sure the content is restricted to the visible screen size, considering any dynamic content like the banner.

I will account for the warning banner:
I will ensure that the page fits 100% of the screen height, regardless of whether the banner is present or removed.
If the banner is dynamic, I will adjust the layout to handle its presence by ensuring the content below adjusts accordingly (e.g., using calc(100vh - bannerHeight)).

I will test responsiveness across devices:
I will test the page across different screen sizes and devices (desktop, tablet, and mobile) to confirm the layout works consistently without requiring a scroll.
I will also ensure that any fixed or sticky elements (like headers or footers) do not interfere with the content fitting on the screen.

I will optimize the layout for potential future changes:
In case other elements like additional banners or notifications are introduced later, I will ensure that the layout is flexible and adjusts dynamically to fit 100% of the screen, even when new elements are added or removed.

I will test with and without the warning banner:
I will verify that the page adapts smoothly when the warning banner is visible and when it is removed.
I will make sure that when the banner is removed, no additional blank space appears and the rest of the content adjusts seamlessly to fill the screen.

I will submit the PR with screenshots and testing details:
After making the necessary adjustments, I will provide screenshots of the page with and without the banner, showing how the content fits 100% of the screen in both cases.

I will document any additional testing steps required to validate that the fix works across different browsers and screen sizes.

**Comment by mariocodecr** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
Check CSS for Full Screen Fit:
Ensure the layout of the page uses height: 100vh or a similar CSS property to make the page fill 100% of the screen height without requiring scrolling, even when the content is minimal.

Adjust for Banner Removal:
Consider the dynamic removal of the top warning banner. Ensure that when the banner is removed, the page properly readjusts to fill the available screen space by updating the CSS to be responsive and reactive to changes in the page structure.

Check for Overflow:
Identify and fix any elements on the page that may cause overflow, which could lead to unwanted scrolling. This could involve revisiting padding, margins, or specific elements that may be pushing the layout beyond the visible screen area.

Test Responsiveness:
Verify that the page maintains its 100% height on different devices and screen sizes (mobile, tablet, desktop). This will ensure that the page fits the screen properly across all possible viewing environments.

Ensure Cross-Browser Compatibility:
Test the page on various browsers (Chrome, Firefox, Safari, Edge) to make sure the changes work consistently and as expected across different environments.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a strong background in front-end web development with a focus on creating responsive and well-structured UI designs using modern CSS and frameworks like React and TypeScript. My experience in working with various layout techniques, including Flexbox and CSS Grid, allows me to create layouts that adjust perfectly to different screen sizes. Additionally, I have dealt with similar issues in the past, where I had to ensure a webpage fits within 100% of the screen without unnecessary scrolling, while also maintaining critical UI components like banners or headers.

By leveraging my skills in CSS layout strategies and responsive design, I can make sure that the page fits 100% of the screen, taking into account different viewports and the presence (or absence) of a warning banner at the top. I am also familiar with tools and techniques to inspect and debug layout issues, ensuring that the solution is optimized for both desktop and mobile screens.



### How I plan on tackling this issue
To ensure the page fits 100% of the screen, I would approach the problem as follows:

Inspect the current layout: I would first inspect the page to identify the elements contributing to the issue. This would involve checking the HTML and body elements, as well as any outer containers or sections that might be preventing the page from fitting the viewport.

Adjust CSS properties: To make the page fit the screen, I would:

Ensure that the html and body elements, along with any parent containers, have their height set to 100%.
If using a flex or grid layout, I would make sure the containers are set to display: flex; or display: grid; and use properties like flex-grow: 1; or min-height: 100vh; (viewport height) to fill the entire screen.
Check for any padding or margins causing overflow and adjust or remove them.
Handle the warning banner: I would ensure the page continues to fit 100% of the screen, whether the warning banner is present or not. This can be done by using dynamic height calculations such as calc(100vh - <banner height>) to maintain a full-page fit.

Test across devices and screen sizes: I would test the updated layout across different devices and screen resolutions to ensure it behaves as expected. If the page includes dynamic content or other interactive elements, I would ensure that their presence doesn’t affect the 100% fit of the screen.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend and blockchain developer with experience building applications. i am confident in my ability to tackle new challenges and drive innovation in this ecosystem.

### How I plan on tackling this issue
To ensure the page fit 100% of the screen i will imply the following below:

1. Adjusting CSS Styles:
   - Set the body and main container height to 100vh to utilize the full viewport height.
   - Ensure margins and paddings do not cause overflow.
2.  Handling  the Warning Banner:
   - Use CSS media queries or JavaScript to adjust the layout dynamically based on the presence of the banner, ensuring the page still fits without scrolling when the banner is removed.
3. Testing Responsiveness:
   - Test the layout on different screen sizes and resolutions to confirm it consistently fits the viewport.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Please can I be assigned this issue? I am a  blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and solidity and Cairo.


### How I plan on tackling this issue
To solve this issue, I’ll take the following steps:
1.⁠ ⁠I’ll set the main container's height to 100vh and adjust the min-height to accommodate any warning banners if necessary.
2.⁠ ⁠⁠I’ll use media queries to maintain layout across different screen sizes.
3.⁠ ⁠⁠I’ll make sure no elements, like warning banners, overlap or push content down.
4.⁠ ⁠⁠I’ll verify that the full-height functionality works correctly on different browsers and devices.
5.⁠ ⁠⁠Lastly, I’ll inspect and adjust any margins or paddings that contribute to height issues.

Please assign me, I’m ready to work.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
 I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will make the page fit 100% of screen
I will create a custom React hook called useFullPageHeight. This hook will use useState to manage the page height and useEffect to calculate and update it. The calculation will account for the warning banner's presence. I will implement a function to compute the height by subtracting the banner's height from the window's inner height. The hook will add a resize event listener to ensure responsiveness. In the main component, I will apply the calculated height using inline styles. This approach will dynamically adjust the page to fit 100% of the screen, with or without the warning banner, and respond to window resizing.

**Comment by Rayan9064** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack Developer and Cairo Developer. I have good experience building web application. I am new to Open Source and want to begin with this project. I am good in React, Typescript, Redux and Context APIs. I can leverage the same to make this a better game for the users. 

### How I plan on tackling this issue
1) Checking the structure of the project and understanding the codebase. 
2) Knowing the tech stack required
3) Finding the area of the problem. 
3) Designing the Figma solution. 
4) Implementing into code. 
5) Testing the code by inspecting in different screen size. 
6) Modify the code when not working as expected. 
7) After successful review, create a pull request.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I would love to work on this issue i contributed previously to this repo and would love to contribute to this issue

### How I plan on tackling this issue
i approach this issue correctly and accurately

**Comment by Agbeleshe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full stack developer with 3 years experience in HTML, CSS JavaScript, node.js React, Typescript and other libraries and frameworks .

### How I plan on tackling this issue
i will love this to be my first contribution on this platform please. firstly I would check if there is any outer element hindering maximum width span if there isn't i will give the identify segment which is affected and style them appropriately by giving a width of 100vw or 100% as styled property.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Fullstack developer

### How I plan on tackling this issue
To make page non-scrollable and display all the content at once,I'll simply just ensure it doesnt exceed a height of 100dvh

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I’m a front-end developer with 3 years of experience transitioning to Web3, and I would love to make my first contribution to this project. I'm excited to take on this issue to challenge myself, learn, and contribute to the project's success. 
I'm also a member of the Dojo Coding CR community, looking forward to applying my skills in this new space while I grow and contribute to this project.


### How I plan on tackling this issue
First, I’ll read through the Contributor Guidelines and README to ensure I understand the project structure, coding standards, and the process I’m following. This will help me align the documentation with the project’s expectations.
I will review the current layout of the page to identify any CSS properties or structural elements that might be causing it to overflow and require scrolling. This includes checking margins, paddings, and any fixed heights that may be limiting the page’s vertical space.
I will modify the CSS to ensure the page utilizes the full height of the viewport. This may involve using properties like height: 100vh for the main container to allow it to take up the entire height of the screen, regardless of the presence of other elements.
I will ensure that the design is responsive. This means verifying that the layout adapts properly across different screen sizes, including desktop, tablet, and mobile views. I will test how the page behaves with various screen resolutions to confirm it maintains a full-screen appearance.
After making these changes, I will test the page both with and without the warning banner at the top. It’s essential to ensure that even if the banner is removed, the page still fits the screen perfectly without requiring any scrolling.
Finally, I will gather feedback from users to ensure the changes meet their expectations and that the user experience is seamless. If further adjustments are needed based on user interactions, I will refine the layout accordingly.
If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi I am a blockchain developer with 3 years experience. Previously contributed to this project and would love to contribute again.

### How I plan on tackling this issue
I would have to check the styling and figure out the best way to tackle the issue.

**Comment by gregemax** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have experience in front-end development using TypeScript and have worked on responsive design projects. My skills in CSS and layout optimization will help ensure the page fits 100% of the screen across different viewports, while maintaining a good user experience.

### How I plan on tackling this issue
I would inspect the page's layout and CSS properties to identify what is causing the overflow. Then, I’d adjust the height and flex properties to ensure the content fits the screen dynamically. I’d test with and without the warning banner to confirm the page remains responsive

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Can I take this? I’ve participated in almost every ODHack, and I already contributed to the StarkLudo project at the last hackathon. I have extensive experience in frontend development. I can handle this task.

### How I plan on tackling this issue
My profile on OD: https://app.onlydust.com/u/melnikga

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I’m a Full Stack JavaScript Developer with a passion for creating gamified blockchain projects. Since I started with OnlyDust, I’ve made 18 contributions to different initiatives, which has really helped me sharpen my skills in building engaging and user-friendly experiences. I’m excited to bring this expertise to our current task.

### How I plan on tackling this issue
I will first analyze the current layout to identify the elements causing the page to not fit the screen properly. Then, I will modify the CSS styles to ensure the page stretches to 100% height and width, providing a seamless view for players.

I’ll pay special attention to the warning banner at the top of the page. It’s important that even if the banner is removed, the page still maintains a full-screen fit. After making these adjustments, I will test the page on various devices and screen sizes to confirm that it looks great and functions well everywhere.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
 have extensive experience in responsive web design, ensuring web applications fit various screen sizes without the need for scrolling. I am skilled in using CSS flexbox and grid layouts, which will allow me to properly adjust page elements to fit 100% of the screen while maintaining the layout, even when dynamic elements like banners are removed. This experience will help ensure the game page is optimized for different devices and screen sizes.


### How I plan on tackling this issue
I would begin by adjusting the CSS of the page layout, using flexbox or grid to ensure that the content dynamically scales to fit the height and width of the screen. I would take the warning banner into account and ensure that, even when removed, the page still fits 100% of the screen without requiring scrolling. Finally, I’d test across various screen sizes to ensure the page is fully responsive and retains its usability.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Whew, looks like a ton of applications up there. Working as a Meme-Driven Dev back at Gobblchain, im left kind of feeling like https://imgflip.com/i/94quwj

with my previous experiences in personal projects and hackathons, I can whip up some real solutions—probably with a one-liner or two and a laugh along the way. [it's my first ODHack :)]


### How I plan on tackling this issue
mhmm i'll fix it with a couple tweaks:

1. Slap height: 100vh; on the main container.
2. Set the banner as position: absolute; top: 0; so it won’t mess with the layout.
3. Flexbox that main content – one side Ludo, other side sidebar.
4. Throw in some overflow: auto; for any scrollable areas.
5. Make it responsive with flex-direction: column; on mobile. 
Done and dusted! ezpz

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a skilled fullstack developer with a wealth of experience in both frontend and backend JavaScript. With a solid foundation in testing,I have mastered frameworks like Mocha, Chai, and Jest to ensure robust, reliable code in every project. In addition to traditional web development, I have a strong background in blockchain technology, with hands-on experience in Solidity for Ethereum-based smart contracts. Moreover, I have delved into the emerging world of StarkNet, working with Cairo, a cutting-edge language tailored for STARKs, making them a versatile developer capable of bridging both traditional and decentralized web applications.

### How I plan on tackling this issue
With my wealth of knowledge and experience this will be a super easy implementation, making the page to fit 100% and maintain a constant responsiveness across all screen

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a front-end and also a blockchain developer 

### How I plan on tackling this issue
I will love to work on this

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
Step 1: Set HTML and Body Height
Set the height of the HTML and body elements to 100%:
Step 2: Set Container Height
Set the height of the container element to 100%:

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
**UI: Full Page Fit**

Hello Starkludo team,

I am **Joel Vargas**, a member of **Dojo Coding**, and I also come from **OnlyDust**. I have experience working with React, SCSS, and Tailwind, specializing in creating responsive and dynamic user interfaces. In the past, I have worked on similar issues where the goal was to ensure the UI fits the full screen size without requiring users to scroll.

I would like to request the assignment of the issue related to making the page fit 100% of the screen. Below is my proposed approach for solving this issue.

### How I plan on tackling this issue
### **Implementation Plan**

**STEP 1: Adjust the Container and Layout**

- I will ensure the main container is using proper sizing CSS properties such as `min-h-screen` or `h-screen` from Tailwind CSS to make the page take up the full height of the screen.
- I will also check and adjust the `html` and `body` tags to ensure they have a `100%` height, and apply `overflow-hidden` to prevent any scrolling unless necessary for content overflow.

**STEP 2: Handle Responsive Design**

- I will make sure the page fits across all screen sizes (desktop, tablet, mobile) by using Tailwind's responsive classes like `md:`, `lg:`, `xl:` for layouts and sizing.
- The content will be structured using flexbox and grid layouts as needed, ensuring all elements, including banners, footers, and content, fit within the viewport without requiring scroll.

**STEP 3: Account for the Warning Banner**

- I will implement a flexible layout that adapts to the presence or absence of the warning banner.
- The page will adjust dynamically whether the banner is visible or removed, ensuring that the layout still covers 100% of the screen.

**STEP 4: Test Across Browsers and Devices**

- I will test the solution on multiple browsers and screen sizes to ensure full compatibility.
- I will use developer tools to simulate different devices and screen resolutions, confirming that no scrolling is required in any scenario.

---

### Technical Stack

- **React**: To handle any layout-related logic or conditional rendering (e.g., handling the presence of the warning banner).
- **SCSS & Tailwind CSS**: For responsive styling and layout management.
- **Flexbox/Grid**: To create fluid layouts that adapt to the content and screen size.

---

### Example Code Outline

```jsx
export default function FullPageLayout() {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Warning Banner */}
      <div className="bg-red-500 p-2 text-white">
        Warning: This is a banner!
      </div>

      {/* Main Content */}
      <div className="flex-grow flex flex-col justify-center items-center">
        <h1 className="text-4xl">Main Content Here</h1>
        <p>This page now fits 100% of the screen.</p>
      </div>

      {/* Footer */}
      <footer className="bg-gray-800 p-4 text-center text-white">
        Footer Content
      </footer>
    </div>
  );
}

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have worked on a few web designs before ensuring that they are fully responsive making it so web applications fit various screen sizes perfectly which I think perfectly resonates with this issue.

### How I plan on tackling this issue
I will start by modifying the page layout's CSS with flexbox or grid to make the content adaptively fill the screen's height and width. I’ll account for the warning banner to ensure that, even if it’s removed, the page still occupies 100% of the screen without scrolling. Lastly, I'll test the layout on different screen sizes to confirm full responsiveness and usability.

I would love to work on this issue, ETC 1-2 days

**Comment by Pvsaint** [comment]
My background and how it can be leveraged: *

I'm a full stack developer (Blockchain and React) with 3years experience in react.
With my 3 years react experience I can handle this issue if assigned to me.

How I would approach the problem?

I'll inspect the current jsx/html structure and CSS, identify which elements are causing overflow or underflow, check for any fixed height containers that might be restricting full-height layout.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged

hello i am a frontend dev and blockchain developer
please can i work on this issue :) 


### How I plan on tackling this issue
To ensure the page fit 100% of the screen i will imply the following below:

- Adjusting CSS Styles:
- Set the body and main container height to 100vh to utilize the full viewport height.
- Ensure margins and paddings do not cause overflow.
- Handling the Warning Banner:

- Use CSS media queries or JavaScript to adjust the layout dynamically based on the presence of the banner, ensuring the page still fits without scrolling when the banner is removed.
- Testing Responsiveness:

Test the layout on different screen sizes and resolutions to confirm it consistently fits the viewport.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello please can i work on this issue :) and would love to be a contributor



### How I plan on tackling this issue
Steps to Implement
Analyze Current Layout:

Review the current CSS styles and HTML structure to identify elements causing overflow or improper sizing.
CSS Adjustments:

Use CSS properties to ensure the main container and body elements take up the full viewport height.
Handle Warning Banner:

Ensure the layout adapts dynamically based on the presence or absence of the warning banner.
