### ISSUE TITLE
Fix lint issue

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#76]
**Description**
Running the command `pnpm run lint` does not exit successfully because of some linting errors in the client.
<img width="1097" alt="image" src="https://github.com/user-attachments/assets/49055866-50cd-40fe-88c8-9e47fb8651a9">

**Action items**
- Fix all errors identified from running `pnpm run lint`
- Verify that the Client CI workflow runs successfully

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello , i am a frontend and blockchain developer , with a strong background in Next.js, Typescript,Javascript,React,and cario.and i am exicted to contribute my skills to this project . i am avaliable to work . please assign me

### How I plan on tackling this issue
 I will approach this issue by the following:
Firstly i will 
1. Run pnpm run lint to identify linting errors.
2. Fix all reported linting issues in the client code.
3.Then re-run pnpm run lint to ensure no errors remain.
4. I will then verify the client CI workflow runs successfully without any failures.

**Comment by mexes20** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello kindly assign me to work on this. Previously worked on the Cl of Raito

https://github.com/keep-starknet-strange/raito/pull/175

ETA: 1 Day

**Comment by vijay-kesanakurthi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am fullstack blockchain developer and  I have experience in Javascript ,Typescript,React, Go, Rust.  This is my first contribution to the starknet ecosystem. So really i want to work on this issue.

### How I plan on tackling this issue
- Identify lint errors by running `pnpm run lint`.
- Read the error messages.
- Fix the code based on error messages.
- Verify the fixed errors.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib please let me work on this issue

### How I plan on tackling this issue
Fix all linting errors identified by running pnpm run lint.
Ensure the Client CI workflow completes successfully after fixing the errors.

**Comment by omsant02** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
these lint issue are mainly due to assignment of a variable but not using it,

i will remove all such and check for logs for any other CI workflow checks or errors

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hey @princeib can i take on this issue

### How I plan on tackling this issue
Fix Linting Errors:

Resolve all errors identified when running pnpm run lint.
Verify CI Workflow:

Ensure that the Client CI workflow completes successfully after fixes.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend and a blockchain developer. I did love to be assigned please

### How I plan on tackling this issue
Here is my plan:
- I will run pnpm run lint to identify all linting issues in the client and resolve them.
- Once the errors are fixed, I will ensure the Client CI workflow runs successfully without any issues.

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a Web and Systems Software Engineer, with extensive experience in writing softwares with performance and memory safety guarantess using systems programming languages such as Rust, GoLang; and TypeScript. I have experience working with linters such as clippy and writing idiomatic programs.

### How I plan on tackling this issue
- I'd ensure I go through every errors reported by the linter one at a time, and testing every fix to ensure I don't break the software, introduce bugs.
- Assert the client CI workflow runs successfully.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 18 contributions across projects in the OnlyDust ecosystem, I’ve developed a strong proficiency in delivering high-quality solutions and tackling complex issues under tight deadlines. My experience spans frontend, backend, smart contract development, and a deep understanding of optimizing and maintaining scalable codebases.

### How I plan on tackling this issue
I’d start by running the command pnpm run lint to identify all the linting errors in the client code. After reviewing the output, I would proceed to fix each of the errors one by one to ensure the code adheres to the established linting rules. Once all the errors are resolved, I would verify that the Client CI workflow runs successfully to ensure everything is functioning as expected.

I expect this task to take about 1 day to complete. This includes time for addressing the linting errors and running the CI workflow to confirm that there are no further issues.
