### ISSUE TITLE
Convert hackmd documentation to Vocs book

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#78]
**Description**
Currently, the documentation for StarkLudo is contained in an HackMd file: https://hackmd.io/m9AjLcheSXClw9ttzHQmVw

**Action Items**
- Create a new [Vocs project](https://vocs.dev/docs/) in a directory named `book`
- Transfer StarkLudo documentation from [the HackMd file](https://hackmd.io/m9AjLcheSXClw9ttzHQmVw) to the newly created Vocs book
- _Use [Dojo book](https://github.com/dojoengine/book) as a guide/inspiration_

**Comment by Iwueseiter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hi @princeibs can I work on this?
I'm a frontend and smart contract developer. I have also written comprehensive docs for project on here that have been merged.
Here is a link to one of the docs I've written: https://github.com/Flex-NFT-Marketplace/Flex-Marketplace-Contract/pull/107


### How I plan on tackling this issue
I will create a new Vocs project in the book directory, the transfer the documentation from the hackMD file as expected.
I will also reference the Dojo book to get it done as expected.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib i would love to take on this issue

### How I plan on tackling this issue
Create Vocs Project: Set up a new Vocs project in a directory named book.
Transfer Documentation: Copy the StarkLudo content from HackMD to the new Vocs book.
Use Dojo Book as Reference: Follow the structure and formatting of the Dojo book as a guide.
Include Language Support: Ensure documentation covers Cairo and Typescript.
Test and Finalize: Review, test, and finalize the Vocs book for completeness and accuracy.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged




I have experience working with technical documentation tools like docs and have previously transferred and organized project documentation from various formats into structured, accessible formats. This skill will help efficiently migrate the StarkLudo documentation to a docs book and maintain clarity.

https://hackmd.io/@Techhunter





### How I plan on tackling this issue
1. **Set up the Vocs Project:** Create a new Vocs project in a directory named `book`.
2. **Review HackMd Content:** Carefully review and analyze the StarkLudo documentation in the HackMd file.
3. **Transfer Documentation:** Transfer the content from HackMd to the Vocs project while maintaining the original structure.
4. **Use Dojo Book for Inspiration:** Refer to the Dojo book structure for guidance on formatting and structuring the content.
5. **Optimize for Clarity:** Make necessary edits to ensure the documentation is clear and consistent, ready for use by developers and contributors.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am  a front end developer and i also have a strong background in documenttion

### How I plan on tackling this issue
I would start by setting up the Vocs project in a directory named "book." Next, I would copy the StarkLudo documentation from HackMD, organizing the content into appropriate sections in Vocs. Using the Dojo book as a reference, I’d format and structure the documentation to ensure consistency and readability.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
@princeib I would love to work on this issue when ODHack starts I have worked on about 6 different documentation issue on different repositories this is my OD Hack portfolio : https://app.onlydust.com/u/Jemiiah I have a very good track record on docs issues here are some of the repositories I have worked on:
Flex-NFT-Marketplace/Flex-Marketplace-Contract#106
dragan2234/worldcoin-scroll-bridge#13
dragan2234/worldcoin-scroll-bridge#11
NethermindEth/StarknetByExample#200

### How I plan on tackling this issue
effectively and accurate with ETA of : 48 hours at most

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I hold a degree in computer science and have worked as a mobile developer with React and JavaScript, two of the Vocs framework's primary technologies. I have experience working with static site generators such as Jekyll and Docusaurus on a number of documentation projects. My knowledge of contemporary web technologies and my experience with frontend development make me a good fit to integrate Vocs and enhance the project's documentation system.


### How I plan on tackling this issue
Studying the Vocs documentation and the present project structure would be my first steps. Next, I would configure Vocs in the project such that it would function with the already-existing markdown files. I would make a vocs.config.js file to alter the look and feel of the website. I would then modify the build procedure to use Vocs to create the static website. For local testing, I would include a dev server script. Lastly, I would provide explicit instructions to the README for installing the software, creating the website, and starting the development server locally. I would make sure the current material is correctly transferred and rendered in the new system during the entire process.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeib i would love to tackle this issue

### How I plan on tackling this issue
Create a New Vocs Project:

Set up a directory named book.
Transfer Documentation:

Move the StarkLudo documentation from the HackMD file to the new Vocs book format.
Reference:

Use the Dojo book as a guide for structure and formatting.

please kindly assign :)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend and a blockchain developer and I will love to contribute to this

### How I plan on tackling this issue
I can get it done

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 18 contributions across projects in the OnlyDust ecosystem, I’ve developed a strong proficiency in delivering high-quality solutions and tackling complex issues under tight deadlines. My experience spans frontend, backend, smart contract development, and a deep understanding of optimizing and maintaining scalable codebases. 

### How I plan on tackling this issue
To start, I’d create a new Vocs project in a directory called "book," which will be the new home for the StarkLudo documentation. I’d then transfer the content from the HackMd file into this new Vocs book, making sure everything is organized and easy to read. I’d take inspiration from the Dojo book to help shape the layout and style, ensuring that the StarkLudo documentation is clear and user-friendly.

I expect this task will take about 2 days to complete. On the first day, I’ll focus on setting up the Vocs project and starting the transfer of the documentation. On the second day, I’ll wrap up the transfer, review everything for formatting, and make any necessary tweaks to ensure it looks great and provides a smooth experience for users.
