### ISSUE TITLE
Create the "Join game" function

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#80]
**Description**
- The join game function should be added to game actions
- The function should allow a player to join a pending game using the game ID.
 - It should take in the game Id and the player color and add the player's username to the game state

**Action Items**
- Create the join game function
- Create the corresponding test cases for the join game function

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello , i am a frontend and blockchain developer , with a strong background in Next.js, Typescript,Javascript,React,and cario.and i am exicted to contribute my skills to this project . i am avaliable to work . please assign me

### How I plan on tackling this issue
 Here is how i intend to approach the problem:

1. Add `joinGame` to `gameActions`:
   - Take gameId,  playerColor , and add the player to the game state.

2. Write tests:
   - Test successful join and edge cases (e.g., invalid `gameId`, taken color).

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have years of experience with TypeScript, Cairo, Flutter, Python, React Native, and mobile application development. I also hold a bachelor's degree in computer science. My experience with these technologies—especially with Cairo and TypeScript—perfectly matches the job requirements.
I'm particularly qualified to take on the work of developing the "Join game" function because of my familiarity with Cairo. I have a lot of experience developing smart contracts and am familiar with the nuances of creating secure, effective code that runs on-chain.


### How I plan on tackling this issue
In order to ensure that the new function integrates easily, I would tackle the problem by first carefully evaluating the current game actions. Next, I would put the join game function into practice, giving careful thought to any potential edge circumstances, including how to handle requests to join games that are full or don't exist.
If all requirements are satisfied, the function would add the player's username to the game state after verifying the game's status and receiving the game ID and player colour as inputs. I'd make sure that errors are handled correctly and release pertinent events for front-end interaction.
Following deployment, I would write thorough test cases covering a range of scenarios, such as successful joins, unsuccessful attempts to join entire games, and incorrect input handling. These testing would guarantee the accuracy and dependability of the function.

**Comment by vijay-kesanakurthi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am fullstack blockchain developer and I have experience in Javascript ,Typescript,React, Go, Rust,Move. 

### How I plan on tackling this issue
- Create a `join_game` function in game actions
- The function take in the game Id and the player color and add the player's username to the game state. 
- Check if the Player color is not taken and game is in pending.

**Comment by omsant02** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
i can see, cuurently the errors are handled using assert and panic in various files,

i have to change all the error handling from assert and panic to custom Error like using 

mod Errors {
    pub const NULL_REWARDS: felt252 = 'Reward amount must be > 0';
    pub const NOT_ENOUGH_REWARDS: felt252 = 'Reward amount must be > balance';
}

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i'm a block chain dev and would love to work on this

### How I plan on tackling this issue
Function Requirements:
Allow a player to join a pending game using the game ID.
Accept the game ID and player color.
Add the player's username to the game state.
Action Items:
Implement the Join Game Function:

Create the function that handles joining a game.
Develop Test Cases:

Write corresponding test cases to ensure the functionality works correctly.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Hello @princeibs I'm a frontend and a blockchain developer and this is something i can work. I did love to be assigned

### How I plan on tackling this issue
Here is how I plan to approach it:
- I will add the function to game actions, taking the game ID and player color, validate if the game is pending, and update the game state with the player's username and color
- I will modify the game state to reflect the player's addition, ensuring everything is handled efficiently
- I will ensure that edge cases like invalid game IDs or a full game are managed gracefully with proper error handling
- I will write unit tests to cover different scenarios, including successful joins and various edge cases

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
Step 1: Understand the Requirements

    The join game function will:
        Allow a player to join a pending game using the game ID.
        Accept the game ID and the player color as parameters.
        Add the player's username to the game state.

Step 2: Implement the Join Game Function

    Define the Function:
        In the gameActions module, create a new function named joinGame.
        This function should accept two parameters: gameId and playerColor.

Step 3: Create Corresponding Test Cases
    Set Up Test Cases:
        Create test cases for the joinGame function.
Step 4: Run the Tests

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a Full Stack Developer with extensive experience in blockchain development, specializing in Next.js, TypeScript, Node.js, and Rust. With over 18 contributions across projects in the OnlyDust ecosystem, I’ve developed a strong proficiency in delivering high-quality solutions and tackling complex issues under tight deadlines. My experience spans frontend, backend, smart contract development, and a deep understanding of optimizing and maintaining scalable codebases.

### How I plan on tackling this issue
First, I’d add the join game function to the game actions. This function will let players join a pending game by using the game ID. It will take the game ID and the player’s color and add the player’s username to the game state. Once I have that working, I’ll write some test cases to make sure everything works well and handles different situations.

I expect to complete this task in about 2 days. On the first day, I’ll focus on building the join game function and making sure it fits with the other game actions. On the second day, I’ll create and run the test cases to confirm that the function works correctly in various scenarios.

**Comment by Pvsaint** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Boss IBS please let me handle this issue.

**Comment by Benjtalkshow** [comment]
Thanks @princeibs
