### ISSUE TITLE
Integrate Dojo burner account

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#82]
**Description**
Dojo burner account allows players to interact with the game and sign transaction without needing to connect their Starknet wallet. Players create burner account that will be stored in the browser and can be reused when next they visit the game. Example of a burner account can be found in the [`dojo-starter` example project](https://book.dojoengine.org/client/sdk/js/getting-started#quickstart)

**Action Items**
- Integrate the burner account to allow players interact with StarkLudo with needing to connect their Starknet wallet

**Comment by kateberryd** [comment]
I w

**Comment by zintarh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I'm a frontend developer 

### How I plan on tackling this issue
I will integrate a burner account system into StarkLudo, allowing players to interact without needing to connect their Starknet wallet. First, I will familiarize myself with the Dojo burner account functionality by reviewing the dojo-starter example project.

I will create a user-friendly interface with a button for players to create a burner account. When clicked, I’ll generate a unique identifier and optionally a public/private key pair, saving this information in local storage for future use. This allows players to perform actions without needing a wallet connection. When a player interacts with the game, I will prepare transaction data and sign it using the burner account's private key.

To facilitate interaction with Starknet, I’ll set up an API or smart contract method to accept signed transactions from burner accounts, ensuring the backend verifies these for authenticity. I’ll check local storage for existing burner accounts when players revisit the game, automatically loading their information, and providing an option to reset or delete the account if needed.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a blockchain developer , and i have experience in html, react , css, javascript , typescript, cario and solidity.

### How I plan on tackling this issue
 i will approach the problem by :
Integrating  a burner account system in StarkLudo that allows players to interact without connecting their Starknet wallet, using local storage for account reuse,doing so by  following the example in the dojo-starter project.
please assign me i am avaliable to work.

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello i would love to work on this issue

### How I plan on tackling this issue
i would solve this by:
Research: Review the dojo-starter project for burner account implementation.
Setup Creation: Implement functionality for players to create burner accounts, storing data in the browser.
Enable Interactions: Allow players to use burner accounts for game interactions without connecting a Starknet wallet.
Session Management: Ensure accounts are reusable across sessions.
User Interface: Update UI for managing burner accounts with clear instructions.
Testing: Verify creation, interaction functionality, and persistence of burner accounts.
Documentation: Document the feature for developers and players.
