### ISSUE TITLE
Implement "Sell account" UI

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#91]
**Description**
UI design: 
![image](https://github.com/user-attachments/assets/1e1ed8c3-65cc-4db2-8b3f-63e9738c0b57)

**Action Items**
- Implement the "Sell account" UI
- Don't bother about the functionality yet, just the UI

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer 

### How I plan on tackling this issue
.

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i am a fronend developer

### How I plan on tackling this issue
To implement the "Sell account" UI, follow these steps:

1. **Create a form layout**: Include fields like "Name o buyer," "Passkey," and "confirm passkey description.
2. Add buttons
3. Style the components

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
i am frontend developer . 

### How I plan on tackling this issue
To implement the "Sell account" UI I will implement the following:

1. Layout Structure: Use a container with appropriate padding and spacing. Inside, include a heading, description, and relevant buttons or input fields. 
2. UI Elements:
   - Heading: A bold title like Sell Account at the top.
   - Description: Use a smaller font for a brief explanatory text below the title.
   - Input Fields: Include inputs for user details (e.g., account name, price) with clear labels.
   - Action Buttons: A Submit button at the bottom.
3. Styling: Match the app’s color scheme, with consistent margins and padding for a clean layout.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Ugo and I am a fullstack dev

### How I plan on tackling this issue


I will Create the "Sell account" UI screen with a title, some info text, a couple input fields for the details, and a main button at the bottom. I'll match our existing style guide for fonts and spacing.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs my name is martin i would love to take on this issue

this is easy to tackle please kindly assign :)

### How I plan on tackling this issue
Task Overview:

Create the UI for the "Sell Account" feature.
i would also make it pixel perfect

**Comment by Kaminar-i** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
hello @princeibs my name is justice i would love to take on this issue please kindly assign

### How I plan on tackling this issue
i would make sure to follow the guide and implement the design to be pixel perfect and responsiveness

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a background in software development with experience in JavaScript, TypeScript, React, HTML, CSS, and Python. As an intermediate frontend developer, I have worked on various projects, including UI design, API integration, and game development

### How I plan on tackling this issue
I will start by using available UI components such as buttons, input fields, and modals from the existing library Material-UI 

Next, I'll structure the layout with a clear title "Sell Account" input fields for necessary details (e.g., Name Of Buyer, passKey, Confirm Passkey), and a "Sell" and "CANCLE" button for form submission.

After that, I'll style the components to match the existing design using tools like Styled Components & CSS Modules. If needed, I will wrap the form in a modal to allow users to open and close the "Sell Account" UI easily.

Lastly, I will ensure the UI is responsive, adapting to different devices by using flexible layouts and media queries.

**Comment by petersdt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am an intermediate frontend developer with experience in JavaScript, TypeScript, React, HTML and CSS. Also worked on integrating smart contract to frontend applications

### How I plan on tackling this issue
I will begin by utilizing available UI components such as buttons, input fields, and modals from the Material-UI library.

Next, I’ll arrange the layout with a clear heading like "Sell Account," along with input fields for required information (e.g., Name of Buyer, passKey, Confirm Passkey), and include "Sell" and "Cancel" buttons for form submission.

Following that, I’ll apply styling to the components to align with the current design, using tools like Styled Components and CSS Modules. If necessary, I’ll place the form inside a modal for easy access to open and close the "Sell Account" UI.

Finally, I’ll make sure the UI is responsive, adjusting smoothly across different devices by implementing flexible layouts and media queries.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will implement the "Sell account" UI based on the provided design. I will focus on ensuring the layout, visuals, and components match the design specifications. This will include structuring the page with appropriate elements like buttons, text fields, and images, paying attention to spacing, colors, and fonts. I will ensure that the UI is responsive and user-friendly. Functionality will be excluded for now, as the task only involves the UI design.

**Comment by muheebyusufbaba1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend developer  with React, HTML , CSS, Javascript who has worked several issues via only dust concerning UI design

### How I plan on tackling this issue

firstly i will begin by utilizing the UI components from the Material-UI library, such as buttons, input fields, and modals. First, I’ll create a clear layout featuring a heading like "Sell Account" along with essential input fields for the required information i.e  Name of Buyer, PassKey, Confirm PassKey).

To facilitate form submission, I will include "Sell" and "Cancel" buttons. Next, I’ll style the components to align with the existing design using tools like Styled Components and CSS Modules. If necessary, I’ll place the form inside a modal for easy access and navigation.

Finally, I will ensure the UI is responsive, enabling it to adapt smoothly across various devices by implementing flexible layouts and media queries

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Full stack dev

### How I plan on tackling this issue
I will follow the figma design to the letter to achieve this design
