### ISSUE TITLE
Implement "Change Pieces" on client

### ISSUE THREAD

**Issue by ibsule** [sivicstudio/starkludo#92]
**Description**
In the toolbox window, there is a page that allows the player change the current game piece. Currently it's not functional. 

**Action Items**
- Implement the page and add the functionality that will allow the player select from a list of available pieces.
- The piece selected by the player should be the current piece in display and available for just for that player during game play.
![image](https://github.com/user-attachments/assets/7354eb43-c9d7-42ed-83c2-6b60aad418a5)

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
@princeibs can I work on this please?
I am a frontend/web3 developer

### How I plan on tackling this issue
To implement the game piece selection functionality in the toolbox window, follow these steps:

1. **Create the UI for piece selection**:
   - Add a dropdown or a list component that displays available game pieces. This can include images or icons representing each piece.
   - Include a button for "Select" to confirm the choice.

2. **Manage state**:
   - Use state management (e.g., React state or a global store) to track the currently selected game piece for each player. 
   - When the player selects a piece, update the state to reflect their choice.

3. **Display the selected piece**:
   - Update the display area to show the currently selected piece in real-time as the player makes their selection.
   - Ensure that the selected piece persists throughout gameplay, only changing when the player selects a new piece.

4. **Implement the functionality**:
   - Add event handlers for the selection and confirmation actions, ensuring the chosen piece is saved and utilized during the game.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I am a frontend and blockchain developer with background in Html, css, cario, solidity, javascript , typescript etc. i hope this issue is assigned to me i am ready to work to achieve what is required .

### How I plan on tackling this issue
To solve this issue, I will take the following steps:

1. Create the UI for the Piece Selection Page:
   - Display a list/grid of available game pieces (images or icons).
   - Make each game piece selectable using buttons or click events.
2. Store the Selected Piece:
   - On piece selection, store the player's choice in a state variable (e.g., selectedPiece).
   - Ensure the selected piece is saved in local storage, player data, or session (depending on your game’s architecture) for persistence during gameplay.
3. Update the Displayed Piece:
   - Dynamically update the current game piece in the player’s view based on selectedPiece (using state management or context, depending on your framework).
4. Integrate Selection in Gameplay:
   - Ensure the selected piece is tied to the player during gameplay by fetching selectedPiece data whenever the player joins the game or when the game starts.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
I have a background in software development with experience in JavaScript, TypeScript, React, HTML, CSS, and Python. As an intermediate frontend developer, I have worked on various projects, including UI design, API integration, and game development.

### How I plan on tackling this issue
- Set Up State Management: Use useState (in React) to track the currently selected game piece for the player. Initialize it with a default piece.

- Display Available Pieces: Render a list of available pieces for the player to choose from. Using map()  i would display al list of avaliable piece and loop over an array of pieces and display each one with an image avaliable in the ui.

-  Handle Piece Selection: Create a function to handle the selection of a piece. When the player selects a piece, update the selectedPiece state.

- Display the Current Piece: Render the currently selected piece dynamically on the screen, showing it as the active piece.

- Persist and Use Piece for Game Play: Store the selected piece in the player's profile or session data, so it is available during gameplay.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.

### How I plan on tackling this issue
I will implement the functionality in the toolbox window that allows players to change their current game piece. I will first create a list of available game pieces from which the player can choose. Then, I will enable the player to select a piece, ensuring that the selected piece updates the current piece in display. This piece will be available exclusively for that player during gameplay. Finally, I will test the implementation to confirm that the piece selection works correctly and is reflected in the game.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
Fullstack developer 

### How I plan on tackling this issue
After looking through the codebase,starkludo has a toolbox window that this will be handled in,I will implement the various pieces players can choose from and the selected piece ensure that it will be persisted during gameplay

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starkludo).

### My background and how it can be leveraged
With experience in developing user interfaces for gaming applications, particularly in player customization, I can efficiently implement the toolbox functionality, allowing players to select and display their game piece smoothly during gameplay.

### How I plan on tackling this issue
I would start by reviewing the existing code for the toolbox window and identifying where the current functionality is missing. Then, I would implement the logic that allows players to select their game piece from the available options, ensuring their choice is reflected in the UI and saved for gameplay. Finally, I would test the feature thoroughly to confirm that the selected piece displays correctly for each player and functions as intended throughout the game.

**Comment by ibsule** [comment]
Closed by #106
